-- Oracle AI Database 26ai compatible baseline. JSON payloads deliberately use
-- CLOB + IS JSON so the schema also works when native JSON binding is unavailable.

CREATE TABLE SPLITO_CURRENCIES (
  CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
  SYMBOL VARCHAR2(12 CHAR),
  MINOR_UNIT NUMBER(1,0) NOT NULL,
  ACTIVE_FLAG CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CONSTRAINT SPLITO_PK_CURRENCIES PRIMARY KEY (CURRENCY_CODE),
  CONSTRAINT SPLITO_CK_CURRENCY_CODE CHECK (CURRENCY_CODE = UPPER(CURRENCY_CODE)),
  CONSTRAINT SPLITO_CK_CURRENCY_MINOR CHECK (MINOR_UNIT BETWEEN 0 AND 3),
  CONSTRAINT SPLITO_CK_CURRENCY_ACTIVE CHECK (ACTIVE_FLAG IN ('Y', 'N'))
);

CREATE TABLE SPLITO_USERS (
  USER_ID RAW(16) NOT NULL,
  EMAIL_NORMALIZED VARCHAR2(320 CHAR) NOT NULL,
  EMAIL_VERIFIED_AT_UTC TIMESTAMP(6),
  PASSWORD_HASH VARCHAR2(512 CHAR),
  DISPLAY_NAME VARCHAR2(120 CHAR) NOT NULL,
  AVATAR_KEY VARCHAR2(512 CHAR),
  LOCALE_CODE VARCHAR2(35 CHAR) DEFAULT 'en-IN' NOT NULL,
  TIMEZONE_NAME VARCHAR2(64 CHAR) DEFAULT 'Asia/Kolkata' NOT NULL,
  DEFAULT_CURRENCY_CODE CHAR(3 CHAR) DEFAULT 'INR' NOT NULL,
  THEME VARCHAR2(10 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  REDUCED_MOTION_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
  SECURITY_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  DELETION_REQUESTED_AT_UTC TIMESTAMP(6),
  ANONYMIZED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_USERS PRIMARY KEY (USER_ID),
  CONSTRAINT SPLITO_UQ_USERS_EMAIL UNIQUE (EMAIL_NORMALIZED),
  CONSTRAINT SPLITO_FK_USERS_CURRENCY FOREIGN KEY (DEFAULT_CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_CK_USERS_EMAIL_LOWER CHECK (EMAIL_NORMALIZED = LOWER(EMAIL_NORMALIZED)),
  CONSTRAINT SPLITO_CK_USERS_THEME CHECK (THEME IN ('LIGHT', 'DARK', 'SYSTEM')),
  CONSTRAINT SPLITO_CK_USERS_MOTION CHECK (REDUCED_MOTION_FLAG IN ('Y', 'N')),
  CONSTRAINT SPLITO_CK_USERS_STATUS CHECK (STATUS IN ('PENDING', 'ACTIVE', 'LOCKED', 'DELETION_PENDING', 'ANONYMIZED')),
  CONSTRAINT SPLITO_CK_USERS_SEC_VERSION CHECK (SECURITY_VERSION >= 1)
);

CREATE TABLE SPLITO_PARTICIPANTS (
  PARTICIPANT_ID RAW(16) NOT NULL,
  USER_ID RAW(16),
  KIND VARCHAR2(10 CHAR) NOT NULL,
  DISPLAY_NAME VARCHAR2(120 CHAR) NOT NULL,
  GUEST_EMAIL_NORMALIZED VARCHAR2(320 CHAR),
  CLAIMED_AT_UTC TIMESTAMP(6),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CREATED_BY_PARTICIPANT_ID RAW(16),
  CONSTRAINT SPLITO_PK_PARTICIPANTS PRIMARY KEY (PARTICIPANT_ID),
  CONSTRAINT SPLITO_UQ_PARTICIPANT_USER UNIQUE (USER_ID),
  CONSTRAINT SPLITO_FK_PARTICIPANT_USER FOREIGN KEY (USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_FK_PARTICIPANT_CREATOR FOREIGN KEY (CREATED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_PARTICIPANT_KIND CHECK (KIND IN ('USER', 'GUEST')),
  CONSTRAINT SPLITO_CK_PARTICIPANT_OWNER CHECK (
    (KIND = 'USER' AND USER_ID IS NOT NULL AND GUEST_EMAIL_NORMALIZED IS NULL) OR
    (KIND = 'GUEST' AND USER_ID IS NULL)
  ),
  CONSTRAINT SPLITO_CK_PARTICIPANT_EMAIL CHECK (
    GUEST_EMAIL_NORMALIZED IS NULL OR GUEST_EMAIL_NORMALIZED = LOWER(GUEST_EMAIL_NORMALIZED)
  )
);

CREATE TABLE SPLITO_USER_PREFERENCES (
  USER_ID RAW(16) NOT NULL,
  NOTIFICATION_JSON CLOB DEFAULT '{}' NOT NULL,
  PRIVACY_JSON CLOB DEFAULT '{}' NOT NULL,
  OFFLINE_ACCESS_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_USER_PREFERENCES PRIMARY KEY (USER_ID),
  CONSTRAINT SPLITO_FK_PREF_USER FOREIGN KEY (USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_CK_PREF_NOTIFY_JSON CHECK (NOTIFICATION_JSON IS JSON),
  CONSTRAINT SPLITO_CK_PREF_PRIVACY_JSON CHECK (PRIVACY_JSON IS JSON),
  CONSTRAINT SPLITO_CK_PREF_OFFLINE CHECK (OFFLINE_ACCESS_FLAG IN ('Y', 'N'))
);

CREATE TABLE SPLITO_AUTH_TOKENS (
  TOKEN_ID RAW(16) NOT NULL,
  USER_ID RAW(16) NOT NULL,
  TOKEN_TYPE VARCHAR2(24 CHAR) NOT NULL,
  TOKEN_HASH RAW(32) NOT NULL,
  EXPIRES_AT_UTC TIMESTAMP(6) NOT NULL,
  CONSUMED_AT_UTC TIMESTAMP(6),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CREATED_IP_HASH RAW(32),
  CONSTRAINT SPLITO_PK_AUTH_TOKENS PRIMARY KEY (TOKEN_ID),
  CONSTRAINT SPLITO_UQ_AUTH_TOKEN_HASH UNIQUE (TOKEN_HASH),
  CONSTRAINT SPLITO_FK_AUTH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_CK_AUTH_TOKEN_TYPE CHECK (TOKEN_TYPE IN ('EMAIL_VERIFY', 'PASSWORD_RESET', 'GUEST_CLAIM')),
  CONSTRAINT SPLITO_CK_AUTH_TOKEN_EXPIRY CHECK (EXPIRES_AT_UTC > CREATED_AT_UTC)
);

CREATE INDEX SPLITO_IX_AUTH_TOKEN_USER ON SPLITO_AUTH_TOKENS (USER_ID, TOKEN_TYPE, CREATED_AT_UTC);
CREATE INDEX SPLITO_IX_AUTH_TOKEN_EXPIRY ON SPLITO_AUTH_TOKENS (EXPIRES_AT_UTC, CONSUMED_AT_UTC);

CREATE TABLE SPLITO_SESSIONS (
  SESSION_ID RAW(16) NOT NULL,
  USER_ID RAW(16) NOT NULL,
  SESSION_TOKEN_HASH RAW(32) NOT NULL,
  CSRF_SECRET_HASH RAW(32) NOT NULL,
  DEVICE_NAME VARCHAR2(200 CHAR),
  USER_AGENT_SUMMARY VARCHAR2(500 CHAR),
  IP_ADDRESS_HASH RAW(32),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  LAST_SEEN_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  EXPIRES_AT_UTC TIMESTAMP(6) NOT NULL,
  REVOKED_AT_UTC TIMESTAMP(6),
  REVOKED_REASON VARCHAR2(200 CHAR),
  ROTATION_COUNTER NUMBER(10,0) DEFAULT 0 NOT NULL,
  CONSTRAINT SPLITO_PK_SESSIONS PRIMARY KEY (SESSION_ID),
  CONSTRAINT SPLITO_UQ_SESSION_TOKEN UNIQUE (SESSION_TOKEN_HASH),
  CONSTRAINT SPLITO_FK_SESSION_USER FOREIGN KEY (USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_CK_SESSION_EXPIRY CHECK (EXPIRES_AT_UTC > CREATED_AT_UTC),
  CONSTRAINT SPLITO_CK_SESSION_ROTATION CHECK (ROTATION_COUNTER >= 0)
);

CREATE INDEX SPLITO_IX_SESSION_USER ON SPLITO_SESSIONS (USER_ID, REVOKED_AT_UTC, EXPIRES_AT_UTC);

CREATE TABLE SPLITO_MFA_METHODS (
  MFA_METHOD_ID RAW(16) NOT NULL,
  USER_ID RAW(16) NOT NULL,
  METHOD_TYPE VARCHAR2(12 CHAR) NOT NULL,
  LABEL VARCHAR2(120 CHAR),
  SECRET_CIPHERTEXT BLOB,
  SECRET_KEY_VERSION VARCHAR2(64 CHAR),
  PASSKEY_CREDENTIAL_ID RAW(1024),
  PASSKEY_PUBLIC_KEY BLOB,
  PASSKEY_SIGN_COUNT NUMBER(19,0),
  VERIFIED_AT_UTC TIMESTAMP(6),
  DISABLED_AT_UTC TIMESTAMP(6),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_MFA_METHODS PRIMARY KEY (MFA_METHOD_ID),
  CONSTRAINT SPLITO_FK_MFA_USER FOREIGN KEY (USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_CK_MFA_TYPE CHECK (METHOD_TYPE IN ('TOTP', 'PASSKEY')),
  CONSTRAINT SPLITO_CK_MFA_MATERIAL CHECK (
    (METHOD_TYPE = 'TOTP' AND SECRET_CIPHERTEXT IS NOT NULL AND SECRET_KEY_VERSION IS NOT NULL AND PASSKEY_CREDENTIAL_ID IS NULL) OR
    (METHOD_TYPE = 'PASSKEY' AND SECRET_CIPHERTEXT IS NULL AND PASSKEY_CREDENTIAL_ID IS NOT NULL AND PASSKEY_PUBLIC_KEY IS NOT NULL)
  ),
  CONSTRAINT SPLITO_CK_MFA_SIGN_COUNT CHECK (PASSKEY_SIGN_COUNT IS NULL OR PASSKEY_SIGN_COUNT >= 0)
);

CREATE UNIQUE INDEX SPLITO_UQ_MFA_PASSKEY ON SPLITO_MFA_METHODS (PASSKEY_CREDENTIAL_ID);
CREATE INDEX SPLITO_IX_MFA_USER ON SPLITO_MFA_METHODS (USER_ID, DISABLED_AT_UTC);

CREATE TABLE SPLITO_RECOVERY_CODES (
  RECOVERY_CODE_ID RAW(16) NOT NULL,
  USER_ID RAW(16) NOT NULL,
  CODE_HASH RAW(32) NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSUMED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_RECOVERY_CODES PRIMARY KEY (RECOVERY_CODE_ID),
  CONSTRAINT SPLITO_UQ_RECOVERY_HASH UNIQUE (CODE_HASH),
  CONSTRAINT SPLITO_FK_RECOVERY_USER FOREIGN KEY (USER_ID) REFERENCES SPLITO_USERS (USER_ID)
);

CREATE TABLE SPLITO_CONTEXTS (
  CONTEXT_ID RAW(16) NOT NULL,
  CONTEXT_TYPE VARCHAR2(10 CHAR) NOT NULL,
  DEFAULT_CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  SIMPLIFICATION_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  ARCHIVED_AT_UTC TIMESTAMP(6),
  VERSION_NO NUMBER(19,0) DEFAULT 1 NOT NULL,
  CONSTRAINT SPLITO_PK_CONTEXTS PRIMARY KEY (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_CONTEXT_CURRENCY FOREIGN KEY (DEFAULT_CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_FK_CONTEXT_CREATOR FOREIGN KEY (CREATED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_CONTEXT_TYPE CHECK (CONTEXT_TYPE IN ('GROUP', 'DIRECT', 'PERSONAL')),
  CONSTRAINT SPLITO_CK_CONTEXT_SIMPLIFY CHECK (SIMPLIFICATION_FLAG IN ('Y', 'N')),
  CONSTRAINT SPLITO_CK_CONTEXT_STATUS CHECK (STATUS IN ('ACTIVE', 'ARCHIVED')),
  CONSTRAINT SPLITO_CK_CONTEXT_VERSION CHECK (VERSION_NO >= 1),
  CONSTRAINT SPLITO_CK_CONTEXT_ARCHIVE CHECK (
    (STATUS = 'ACTIVE' AND ARCHIVED_AT_UTC IS NULL) OR
    (STATUS = 'ARCHIVED' AND ARCHIVED_AT_UTC IS NOT NULL)
  )
);

CREATE TABLE SPLITO_GROUPS (
  GROUP_ID RAW(16) NOT NULL,
  CONTEXT_ID RAW(16) NOT NULL,
  GROUP_NAME VARCHAR2(160 CHAR) NOT NULL,
  DESCRIPTION VARCHAR2(1000 CHAR),
  GROUP_TYPE VARCHAR2(20 CHAR) DEFAULT 'OTHER' NOT NULL,
  IMAGE_KEY VARCHAR2(512 CHAR),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_GROUPS PRIMARY KEY (GROUP_ID),
  CONSTRAINT SPLITO_UQ_GROUP_CONTEXT UNIQUE (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_GROUP_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_CK_GROUP_TYPE CHECK (GROUP_TYPE IN ('HOME', 'TRIP', 'COUPLE', 'FAMILY', 'PROJECT', 'OTHER'))
);

CREATE TABLE SPLITO_CONTEXT_MEMBERS (
  MEMBERSHIP_ID RAW(16) NOT NULL,
  CONTEXT_ID RAW(16) NOT NULL,
  PARTICIPANT_ID RAW(16) NOT NULL,
  MEMBER_ROLE VARCHAR2(10 CHAR) NOT NULL,
  STATUS VARCHAR2(10 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  ALLOCATION_ORDER NUMBER(10,0) NOT NULL,
  JOINED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  LEFT_AT_UTC TIMESTAMP(6),
  ADDED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  VERSION_NO NUMBER(19,0) DEFAULT 1 NOT NULL,
  CONSTRAINT SPLITO_PK_CONTEXT_MEMBERS PRIMARY KEY (MEMBERSHIP_ID),
  CONSTRAINT SPLITO_FK_MEMBER_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_MEMBER_PARTICIPANT FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_MEMBER_ADDER FOREIGN KEY (ADDED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_MEMBER_ROLE CHECK (MEMBER_ROLE IN ('OWNER', 'ADMIN', 'MEMBER')),
  CONSTRAINT SPLITO_CK_MEMBER_STATUS CHECK (STATUS IN ('ACTIVE', 'LEFT', 'REMOVED')),
  CONSTRAINT SPLITO_CK_MEMBER_ORDER CHECK (ALLOCATION_ORDER >= 0),
  CONSTRAINT SPLITO_CK_MEMBER_VERSION CHECK (VERSION_NO >= 1),
  CONSTRAINT SPLITO_CK_MEMBER_LEFT CHECK (
    (STATUS = 'ACTIVE' AND LEFT_AT_UTC IS NULL) OR
    (STATUS IN ('LEFT', 'REMOVED') AND LEFT_AT_UTC IS NOT NULL)
  )
);

CREATE UNIQUE INDEX SPLITO_UQ_ACTIVE_CONTEXT_MEMBER ON SPLITO_CONTEXT_MEMBERS (
  CASE WHEN STATUS = 'ACTIVE' THEN CONTEXT_ID END,
  CASE WHEN STATUS = 'ACTIVE' THEN PARTICIPANT_ID END
);
CREATE UNIQUE INDEX SPLITO_UQ_ACTIVE_ALLOC_ORDER ON SPLITO_CONTEXT_MEMBERS (
  CASE WHEN STATUS = 'ACTIVE' THEN CONTEXT_ID END,
  CASE WHEN STATUS = 'ACTIVE' THEN ALLOCATION_ORDER END
);
CREATE INDEX SPLITO_IX_MEMBER_PARTICIPANT ON SPLITO_CONTEXT_MEMBERS (PARTICIPANT_ID, STATUS, CONTEXT_ID);

CREATE TABLE SPLITO_DEFAULT_SPLITS (
  DEFAULT_SPLIT_ID RAW(16) NOT NULL,
  OWNER_PARTICIPANT_ID RAW(16),
  CONTEXT_ID RAW(16),
  SPLIT_NAME VARCHAR2(120 CHAR) NOT NULL,
  SPLIT_METHOD VARCHAR2(16 CHAR) NOT NULL,
  INPUTS_JSON CLOB NOT NULL,
  PRIMARY_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  VERSION_NO NUMBER(19,0) DEFAULT 1 NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_DEFAULT_SPLITS PRIMARY KEY (DEFAULT_SPLIT_ID),
  CONSTRAINT SPLITO_FK_DEF_SPLIT_OWNER FOREIGN KEY (OWNER_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_DEF_SPLIT_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_CK_DEF_SPLIT_SCOPE CHECK (
    (OWNER_PARTICIPANT_ID IS NOT NULL AND CONTEXT_ID IS NULL) OR
    (OWNER_PARTICIPANT_ID IS NULL AND CONTEXT_ID IS NOT NULL)
  ),
  CONSTRAINT SPLITO_CK_DEF_SPLIT_METHOD CHECK (SPLIT_METHOD IN ('EQUAL', 'EXACT', 'PERCENTAGE', 'SHARES', 'ADJUSTMENTS', 'ITEMIZED')),
  CONSTRAINT SPLITO_CK_DEF_SPLIT_JSON CHECK (INPUTS_JSON IS JSON),
  CONSTRAINT SPLITO_CK_DEF_SPLIT_PRIMARY CHECK (PRIMARY_FLAG IN ('Y', 'N')),
  CONSTRAINT SPLITO_CK_DEF_SPLIT_VERSION CHECK (VERSION_NO >= 1)
);

CREATE INDEX SPLITO_IX_DEF_SPLIT_OWNER ON SPLITO_DEFAULT_SPLITS (OWNER_PARTICIPANT_ID, PRIMARY_FLAG);
CREATE INDEX SPLITO_IX_DEF_SPLIT_CONTEXT ON SPLITO_DEFAULT_SPLITS (CONTEXT_ID, PRIMARY_FLAG);

CREATE TABLE SPLITO_INVITATIONS (
  INVITATION_ID RAW(16) NOT NULL,
  INVITATION_TYPE VARCHAR2(12 CHAR) NOT NULL,
  CONTEXT_ID RAW(16),
  INVITER_PARTICIPANT_ID RAW(16) NOT NULL,
  INVITEE_EMAIL_NORMALIZED VARCHAR2(320 CHAR),
  INVITEE_PARTICIPANT_ID RAW(16),
  TOKEN_HASH RAW(32) NOT NULL,
  STATUS VARCHAR2(10 CHAR) DEFAULT 'PENDING' NOT NULL,
  EXPIRES_AT_UTC TIMESTAMP(6) NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  RESPONDED_AT_UTC TIMESTAMP(6),
  REVOKED_AT_UTC TIMESTAMP(6),
  RESEND_COUNT NUMBER(5,0) DEFAULT 0 NOT NULL,
  CONSTRAINT SPLITO_PK_INVITATIONS PRIMARY KEY (INVITATION_ID),
  CONSTRAINT SPLITO_UQ_INVITATION_TOKEN UNIQUE (TOKEN_HASH),
  CONSTRAINT SPLITO_FK_INVITE_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_INVITE_INVITER FOREIGN KEY (INVITER_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_INVITE_INVITEE FOREIGN KEY (INVITEE_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_INVITE_TYPE CHECK (INVITATION_TYPE IN ('FRIEND', 'GROUP', 'GUEST_CLAIM')),
  CONSTRAINT SPLITO_CK_INVITE_STATUS CHECK (STATUS IN ('PENDING', 'ACCEPTED', 'REJECTED', 'REVOKED', 'EXPIRED')),
  CONSTRAINT SPLITO_CK_INVITE_EMAIL CHECK (
    INVITEE_EMAIL_NORMALIZED IS NULL OR INVITEE_EMAIL_NORMALIZED = LOWER(INVITEE_EMAIL_NORMALIZED)
  ),
  CONSTRAINT SPLITO_CK_INVITE_TARGET CHECK (
    INVITEE_EMAIL_NORMALIZED IS NOT NULL OR INVITEE_PARTICIPANT_ID IS NOT NULL
  ),
  CONSTRAINT SPLITO_CK_INVITE_EXPIRY CHECK (EXPIRES_AT_UTC > CREATED_AT_UTC),
  CONSTRAINT SPLITO_CK_INVITE_RESENDS CHECK (RESEND_COUNT >= 0)
);

CREATE INDEX SPLITO_IX_INVITE_EMAIL ON SPLITO_INVITATIONS (INVITEE_EMAIL_NORMALIZED, STATUS, EXPIRES_AT_UTC);
CREATE INDEX SPLITO_IX_INVITE_CONTEXT ON SPLITO_INVITATIONS (CONTEXT_ID, STATUS, CREATED_AT_UTC);

CREATE TABLE SPLITO_FRIENDSHIPS (
  FRIENDSHIP_ID RAW(16) NOT NULL,
  PARTICIPANT_LOW_ID RAW(16) NOT NULL,
  PARTICIPANT_HIGH_ID RAW(16) NOT NULL,
  STATUS VARCHAR2(10 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  ENDED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_FRIENDSHIPS PRIMARY KEY (FRIENDSHIP_ID),
  CONSTRAINT SPLITO_UQ_FRIEND_PAIR UNIQUE (PARTICIPANT_LOW_ID, PARTICIPANT_HIGH_ID),
  CONSTRAINT SPLITO_FK_FRIEND_LOW FOREIGN KEY (PARTICIPANT_LOW_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_FRIEND_HIGH FOREIGN KEY (PARTICIPANT_HIGH_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_FRIEND_ORDER CHECK (RAWTOHEX(PARTICIPANT_LOW_ID) < RAWTOHEX(PARTICIPANT_HIGH_ID)),
  CONSTRAINT SPLITO_CK_FRIEND_STATUS CHECK (STATUS IN ('ACTIVE', 'REMOVED')),
  CONSTRAINT SPLITO_CK_FRIEND_ENDED CHECK (
    (STATUS = 'ACTIVE' AND ENDED_AT_UTC IS NULL) OR
    (STATUS = 'REMOVED' AND ENDED_AT_UTC IS NOT NULL)
  )
);

INSERT INTO SPLITO_CURRENCIES (CURRENCY_CODE, DISPLAY_NAME, SYMBOL, MINOR_UNIT) VALUES ('INR', 'Indian Rupee', '₹', 2);
INSERT INTO SPLITO_CURRENCIES (CURRENCY_CODE, DISPLAY_NAME, SYMBOL, MINOR_UNIT) VALUES ('USD', 'US Dollar', '$', 2);
INSERT INTO SPLITO_CURRENCIES (CURRENCY_CODE, DISPLAY_NAME, SYMBOL, MINOR_UNIT) VALUES ('EUR', 'Euro', '€', 2);
INSERT INTO SPLITO_CURRENCIES (CURRENCY_CODE, DISPLAY_NAME, SYMBOL, MINOR_UNIT) VALUES ('GBP', 'Pound Sterling', '£', 2);
INSERT INTO SPLITO_CURRENCIES (CURRENCY_CODE, DISPLAY_NAME, SYMBOL, MINOR_UNIT) VALUES ('JPY', 'Japanese Yen', '¥', 0);
INSERT INTO SPLITO_CURRENCIES (CURRENCY_CODE, DISPLAY_NAME, SYMBOL, MINOR_UNIT) VALUES ('KWD', 'Kuwaiti Dinar', 'د.ك', 3);

GRANT SELECT ON SPLITO_CURRENCIES TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_USERS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_PARTICIPANTS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_USER_PREFERENCES TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_AUTH_TOKENS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_SESSIONS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_MFA_METHODS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_RECOVERY_CODES TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_CONTEXTS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_GROUPS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_CONTEXT_MEMBERS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_DEFAULT_SPLITS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_INVITATIONS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_FRIENDSHIPS TO SPLITO_APP;
