CREATE TABLE SPLITO_EXPENSES (
  EXPENSE_ID RAW(16) NOT NULL,
  CONTEXT_ID RAW(16) NOT NULL,
  DESCRIPTION VARCHAR2(300 CHAR) NOT NULL,
  CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  EXPENSE_DATE DATE NOT NULL,
  BUSINESS_TIMEZONE VARCHAR2(64 CHAR) NOT NULL,
  CATEGORY_CODE VARCHAR2(50 CHAR) NOT NULL,
  STATUS VARCHAR2(10 CHAR) DEFAULT 'DRAFT' NOT NULL,
  CURRENT_REVISION_ID RAW(16),
  VERSION_NO NUMBER(19,0) DEFAULT 1 NOT NULL,
  CREATED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  VOIDED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_EXPENSES PRIMARY KEY (EXPENSE_ID),
  CONSTRAINT SPLITO_FK_EXPENSE_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_EXPENSE_CURRENCY FOREIGN KEY (CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_FK_EXPENSE_CREATOR FOREIGN KEY (CREATED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_EXPENSE_STATUS CHECK (STATUS IN ('DRAFT', 'POSTED', 'VOIDED')),
  CONSTRAINT SPLITO_CK_EXPENSE_DATE CHECK (EXPENSE_DATE = TRUNC(EXPENSE_DATE)),
  CONSTRAINT SPLITO_CK_EXPENSE_VERSION CHECK (VERSION_NO >= 1),
  CONSTRAINT SPLITO_CK_EXPENSE_VOIDED CHECK (
    (STATUS <> 'VOIDED' AND VOIDED_AT_UTC IS NULL) OR
    (STATUS = 'VOIDED' AND VOIDED_AT_UTC IS NOT NULL)
  )
);

CREATE INDEX SPLITO_IX_EXPENSE_CONTEXT_PAGE ON SPLITO_EXPENSES (
  CONTEXT_ID, EXPENSE_DATE DESC, CREATED_AT_UTC DESC, EXPENSE_ID
);
CREATE INDEX SPLITO_IX_EXPENSE_CREATOR ON SPLITO_EXPENSES (CREATED_BY_PARTICIPANT_ID, CREATED_AT_UTC DESC);
CREATE INDEX SPLITO_IX_EXPENSE_FILTERS ON SPLITO_EXPENSES (CONTEXT_ID, CURRENCY_CODE, CATEGORY_CODE, STATUS, EXPENSE_DATE);

CREATE TABLE SPLITO_EXPENSE_REVISIONS (
  REVISION_ID RAW(16) NOT NULL,
  EXPENSE_ID RAW(16) NOT NULL,
  REVISION_NO NUMBER(19,0) NOT NULL,
  TOTAL_MINOR NUMBER(19,0) NOT NULL,
  SPLIT_METHOD VARCHAR2(16 CHAR) NOT NULL,
  ALGORITHM_VERSION VARCHAR2(40 CHAR) NOT NULL,
  ORIGINAL_INPUTS_JSON CLOB NOT NULL,
  NOTES_TEXT VARCHAR2(4000 CHAR),
  PREVIOUS_REVISION_ID RAW(16),
  CREATED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CHANGE_REASON VARCHAR2(500 CHAR),
  CONSTRAINT SPLITO_PK_EXPENSE_REVISIONS PRIMARY KEY (REVISION_ID),
  CONSTRAINT SPLITO_UQ_EXPENSE_REVISION UNIQUE (EXPENSE_ID, REVISION_NO),
  CONSTRAINT SPLITO_FK_REVISION_EXPENSE FOREIGN KEY (EXPENSE_ID) REFERENCES SPLITO_EXPENSES (EXPENSE_ID),
  CONSTRAINT SPLITO_FK_REVISION_PREVIOUS FOREIGN KEY (PREVIOUS_REVISION_ID)
    REFERENCES SPLITO_EXPENSE_REVISIONS (REVISION_ID),
  CONSTRAINT SPLITO_FK_REVISION_CREATOR FOREIGN KEY (CREATED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_REVISION_NO CHECK (REVISION_NO >= 1),
  CONSTRAINT SPLITO_CK_REVISION_TOTAL CHECK (TOTAL_MINOR BETWEEN 1 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_REVISION_METHOD CHECK (SPLIT_METHOD IN ('EQUAL', 'EXACT', 'PERCENTAGE', 'SHARES', 'ADJUSTMENTS', 'ITEMIZED')),
  CONSTRAINT SPLITO_CK_REVISION_INPUTS CHECK (ORIGINAL_INPUTS_JSON IS JSON)
);

ALTER TABLE SPLITO_EXPENSES ADD CONSTRAINT SPLITO_FK_EXPENSE_CURRENT_REV FOREIGN KEY (CURRENT_REVISION_ID)
  REFERENCES SPLITO_EXPENSE_REVISIONS (REVISION_ID);

CREATE TABLE SPLITO_EXPENSE_PAYERS (
  EXPENSE_PAYER_ID RAW(16) NOT NULL,
  REVISION_ID RAW(16) NOT NULL,
  PARTICIPANT_ID RAW(16) NOT NULL,
  PAID_MINOR NUMBER(19,0) NOT NULL,
  ALLOCATION_ORDER NUMBER(10,0) NOT NULL,
  CONSTRAINT SPLITO_PK_EXPENSE_PAYERS PRIMARY KEY (EXPENSE_PAYER_ID),
  CONSTRAINT SPLITO_UQ_EXPENSE_PAYER UNIQUE (REVISION_ID, PARTICIPANT_ID),
  CONSTRAINT SPLITO_UQ_EXP_PAYER_ORDER UNIQUE (REVISION_ID, ALLOCATION_ORDER),
  CONSTRAINT SPLITO_FK_PAYER_REVISION FOREIGN KEY (REVISION_ID)
    REFERENCES SPLITO_EXPENSE_REVISIONS (REVISION_ID),
  CONSTRAINT SPLITO_FK_PAYER_PARTICIPANT FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_PAYER_AMOUNT CHECK (PAID_MINOR BETWEEN 0 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_PAYER_ORDER CHECK (ALLOCATION_ORDER >= 0)
);

CREATE INDEX SPLITO_IX_PAYER_PARTICIPANT ON SPLITO_EXPENSE_PAYERS (PARTICIPANT_ID, REVISION_ID);

CREATE TABLE SPLITO_EXPENSE_SHARES (
  EXPENSE_SHARE_ID RAW(16) NOT NULL,
  REVISION_ID RAW(16) NOT NULL,
  PARTICIPANT_ID RAW(16) NOT NULL,
  OWED_MINOR NUMBER(19,0) NOT NULL,
  ALLOCATION_ORDER NUMBER(10,0) NOT NULL,
  INPUT_VALUE_DECIMAL VARCHAR2(80 CHAR),
  CONSTRAINT SPLITO_PK_EXPENSE_SHARES PRIMARY KEY (EXPENSE_SHARE_ID),
  CONSTRAINT SPLITO_UQ_EXPENSE_SHARE UNIQUE (REVISION_ID, PARTICIPANT_ID),
  CONSTRAINT SPLITO_UQ_EXP_SHARE_ORDER UNIQUE (REVISION_ID, ALLOCATION_ORDER),
  CONSTRAINT SPLITO_FK_SHARE_REVISION FOREIGN KEY (REVISION_ID)
    REFERENCES SPLITO_EXPENSE_REVISIONS (REVISION_ID),
  CONSTRAINT SPLITO_FK_SHARE_PARTICIPANT FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_SHARE_AMOUNT CHECK (OWED_MINOR BETWEEN 0 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_SHARE_ORDER CHECK (ALLOCATION_ORDER >= 0)
);

CREATE INDEX SPLITO_IX_SHARE_PARTICIPANT ON SPLITO_EXPENSE_SHARES (PARTICIPANT_ID, REVISION_ID);

CREATE TABLE SPLITO_EXPENSE_ITEMS (
  EXPENSE_ITEM_ID RAW(16) NOT NULL,
  REVISION_ID RAW(16) NOT NULL,
  ITEM_ORDER NUMBER(10,0) NOT NULL,
  DESCRIPTION VARCHAR2(500 CHAR) NOT NULL,
  QUANTITY_DECIMAL VARCHAR2(80 CHAR) DEFAULT '1' NOT NULL,
  GROSS_MINOR NUMBER(19,0) NOT NULL,
  DISCOUNT_MINOR NUMBER(19,0) DEFAULT 0 NOT NULL,
  TAX_MINOR NUMBER(19,0) DEFAULT 0 NOT NULL,
  SERVICE_CHARGE_MINOR NUMBER(19,0) DEFAULT 0 NOT NULL,
  TIP_MINOR NUMBER(19,0) DEFAULT 0 NOT NULL,
  SOURCE_CONFIDENCE_DECIMAL VARCHAR2(40 CHAR),
  CONSTRAINT SPLITO_PK_EXPENSE_ITEMS PRIMARY KEY (EXPENSE_ITEM_ID),
  CONSTRAINT SPLITO_UQ_EXPENSE_ITEM_ORDER UNIQUE (REVISION_ID, ITEM_ORDER),
  CONSTRAINT SPLITO_FK_ITEM_REVISION FOREIGN KEY (REVISION_ID)
    REFERENCES SPLITO_EXPENSE_REVISIONS (REVISION_ID),
  CONSTRAINT SPLITO_CK_ITEM_ORDER CHECK (ITEM_ORDER >= 0),
  CONSTRAINT SPLITO_CK_ITEM_GROSS CHECK (GROSS_MINOR BETWEEN 0 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_ITEM_DISCOUNT CHECK (DISCOUNT_MINOR BETWEEN 0 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_ITEM_TAX CHECK (TAX_MINOR BETWEEN 0 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_ITEM_SERVICE CHECK (SERVICE_CHARGE_MINOR BETWEEN 0 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_ITEM_TIP CHECK (TIP_MINOR BETWEEN 0 AND 9999999999999999999)
);

CREATE TABLE SPLITO_ITEM_ALLOCATIONS (
  ITEM_ALLOCATION_ID RAW(16) NOT NULL,
  EXPENSE_ITEM_ID RAW(16) NOT NULL,
  PARTICIPANT_ID RAW(16) NOT NULL,
  OWED_MINOR NUMBER(19,0) NOT NULL,
  ALLOCATION_ORDER NUMBER(10,0) NOT NULL,
  CONSTRAINT SPLITO_PK_ITEM_ALLOCATIONS PRIMARY KEY (ITEM_ALLOCATION_ID),
  CONSTRAINT SPLITO_UQ_ITEM_ALLOCATION UNIQUE (EXPENSE_ITEM_ID, PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_ITEM_ALLOC_ITEM FOREIGN KEY (EXPENSE_ITEM_ID)
    REFERENCES SPLITO_EXPENSE_ITEMS (EXPENSE_ITEM_ID),
  CONSTRAINT SPLITO_FK_ITEM_ALLOC_PART FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_ITEM_ALLOC_AMOUNT CHECK (OWED_MINOR BETWEEN 0 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_ITEM_ALLOC_ORDER CHECK (ALLOCATION_ORDER >= 0)
);

CREATE TABLE SPLITO_LEDGER_BATCHES (
  BATCH_ID RAW(16) NOT NULL,
  CONTEXT_ID RAW(16) NOT NULL,
  CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  BATCH_TYPE VARCHAR2(24 CHAR) NOT NULL,
  SOURCE_TYPE VARCHAR2(24 CHAR) NOT NULL,
  SOURCE_ID RAW(16) NOT NULL,
  SOURCE_REVISION_ID RAW(16),
  REVERSES_BATCH_ID RAW(16),
  IDEMPOTENCY_KEY_ID RAW(16),
  ACTOR_PARTICIPANT_ID RAW(16) NOT NULL,
  POSTED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_LEDGER_BATCHES PRIMARY KEY (BATCH_ID),
  CONSTRAINT SPLITO_UQ_LEDGER_REVERSAL UNIQUE (REVERSES_BATCH_ID),
  CONSTRAINT SPLITO_FK_LEDGER_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_LEDGER_CURRENCY FOREIGN KEY (CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_FK_LEDGER_REVERSES FOREIGN KEY (REVERSES_BATCH_ID)
    REFERENCES SPLITO_LEDGER_BATCHES (BATCH_ID),
  CONSTRAINT SPLITO_FK_LEDGER_ACTOR FOREIGN KEY (ACTOR_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_LEDGER_BATCH_TYPE CHECK (BATCH_TYPE IN (
    'EXPENSE', 'REVERSAL', 'REFUND', 'SETTLEMENT', 'CONVERSION_OUT', 'CONVERSION_IN', 'CORRECTION'
  )),
  CONSTRAINT SPLITO_CK_LEDGER_SOURCE_TYPE CHECK (SOURCE_TYPE IN (
    'EXPENSE', 'REFUND', 'SETTLEMENT', 'CONVERSION', 'CORRECTION'
  )),
  CONSTRAINT SPLITO_CK_LEDGER_SELF_REV CHECK (REVERSES_BATCH_ID IS NULL OR REVERSES_BATCH_ID <> BATCH_ID)
);

CREATE INDEX SPLITO_IX_LEDGER_SOURCE ON SPLITO_LEDGER_BATCHES (SOURCE_TYPE, SOURCE_ID, POSTED_AT_UTC);
CREATE INDEX SPLITO_IX_LEDGER_CONTEXT ON SPLITO_LEDGER_BATCHES (CONTEXT_ID, CURRENCY_CODE, POSTED_AT_UTC, BATCH_ID);

CREATE TABLE SPLITO_LEDGER_POSTINGS (
  POSTING_ID RAW(16) NOT NULL,
  BATCH_ID RAW(16) NOT NULL,
  PARTICIPANT_ID RAW(16) NOT NULL,
  AMOUNT_MINOR_SIGNED NUMBER(19,0) NOT NULL,
  POSTING_ORDER NUMBER(10,0) NOT NULL,
  CONSTRAINT SPLITO_PK_LEDGER_POSTINGS PRIMARY KEY (POSTING_ID),
  CONSTRAINT SPLITO_UQ_LEDGER_PARTICIPANT UNIQUE (BATCH_ID, PARTICIPANT_ID),
  CONSTRAINT SPLITO_UQ_LEDGER_ORDER UNIQUE (BATCH_ID, POSTING_ORDER),
  CONSTRAINT SPLITO_FK_POSTING_BATCH FOREIGN KEY (BATCH_ID) REFERENCES SPLITO_LEDGER_BATCHES (BATCH_ID),
  CONSTRAINT SPLITO_FK_POSTING_PARTICIPANT FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_POSTING_AMOUNT CHECK (
    AMOUNT_MINOR_SIGNED BETWEEN -9999999999999999999 AND 9999999999999999999 AND
    AMOUNT_MINOR_SIGNED <> 0
  ),
  CONSTRAINT SPLITO_CK_POSTING_ORDER CHECK (POSTING_ORDER >= 0)
);

CREATE INDEX SPLITO_IX_POSTING_PARTICIPANT ON SPLITO_LEDGER_POSTINGS (PARTICIPANT_ID, BATCH_ID);

CREATE TABLE SPLITO_EXPENSE_OBLIGATIONS (
  OBLIGATION_ID RAW(16) NOT NULL,
  REVISION_ID RAW(16) NOT NULL,
  DEBTOR_PARTICIPANT_ID RAW(16) NOT NULL,
  CREDITOR_PARTICIPANT_ID RAW(16) NOT NULL,
  AMOUNT_MINOR NUMBER(19,0) NOT NULL,
  MATCH_ORDER NUMBER(10,0) NOT NULL,
  ALGORITHM_VERSION VARCHAR2(40 CHAR) NOT NULL,
  CONSTRAINT SPLITO_PK_EXPENSE_OBLIGATIONS PRIMARY KEY (OBLIGATION_ID),
  CONSTRAINT SPLITO_UQ_OBLIGATION_ORDER UNIQUE (REVISION_ID, MATCH_ORDER),
  CONSTRAINT SPLITO_FK_OBLIGATION_REVISION FOREIGN KEY (REVISION_ID)
    REFERENCES SPLITO_EXPENSE_REVISIONS (REVISION_ID),
  CONSTRAINT SPLITO_FK_OBLIGATION_DEBTOR FOREIGN KEY (DEBTOR_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_OBLIGATION_CREDITOR FOREIGN KEY (CREDITOR_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_OBLIGATION_AMOUNT CHECK (AMOUNT_MINOR BETWEEN 1 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_OBLIGATION_PARTIES CHECK (DEBTOR_PARTICIPANT_ID <> CREDITOR_PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_OBLIGATION_ORDER CHECK (MATCH_ORDER >= 0)
);

CREATE INDEX SPLITO_IX_OBLIGATION_DEBTOR ON SPLITO_EXPENSE_OBLIGATIONS (DEBTOR_PARTICIPANT_ID, REVISION_ID);
CREATE INDEX SPLITO_IX_OBLIGATION_CREDITOR ON SPLITO_EXPENSE_OBLIGATIONS (CREDITOR_PARTICIPANT_ID, REVISION_ID);

CREATE TABLE SPLITO_BALANCE_PROJECTIONS (
  CONTEXT_ID RAW(16) NOT NULL,
  PARTICIPANT_ID RAW(16) NOT NULL,
  CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  NET_MINOR_SIGNED NUMBER(19,0) DEFAULT 0 NOT NULL,
  PROJECTION_VERSION NUMBER(19,0) DEFAULT 0 NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_BALANCE_PROJECTIONS PRIMARY KEY (CONTEXT_ID, PARTICIPANT_ID, CURRENCY_CODE),
  CONSTRAINT SPLITO_FK_BALANCE_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_BALANCE_PARTICIPANT FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_BALANCE_CURRENCY FOREIGN KEY (CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_CK_BALANCE_AMOUNT CHECK (
    NET_MINOR_SIGNED BETWEEN -9999999999999999999 AND 9999999999999999999
  ),
  CONSTRAINT SPLITO_CK_BALANCE_VERSION CHECK (PROJECTION_VERSION >= 0)
);

CREATE INDEX SPLITO_IX_BALANCE_PARTICIPANT ON SPLITO_BALANCE_PROJECTIONS (PARTICIPANT_ID, CURRENCY_CODE, CONTEXT_ID);

CREATE TABLE SPLITO_BILATERAL_PROJECTIONS (
  CONTEXT_ID RAW(16) NOT NULL,
  PARTICIPANT_LOW_ID RAW(16) NOT NULL,
  PARTICIPANT_HIGH_ID RAW(16) NOT NULL,
  CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  LOW_OWES_HIGH_MINOR_SIGNED NUMBER(19,0) NOT NULL,
  PROJECTION_VERSION NUMBER(19,0) DEFAULT 0 NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_BILATERAL_PROJ PRIMARY KEY (
    CONTEXT_ID, PARTICIPANT_LOW_ID, PARTICIPANT_HIGH_ID, CURRENCY_CODE
  ),
  CONSTRAINT SPLITO_FK_BILATERAL_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_BILATERAL_LOW FOREIGN KEY (PARTICIPANT_LOW_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_BILATERAL_HIGH FOREIGN KEY (PARTICIPANT_HIGH_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_BILATERAL_CURRENCY FOREIGN KEY (CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_CK_BILATERAL_ORDER CHECK (RAWTOHEX(PARTICIPANT_LOW_ID) < RAWTOHEX(PARTICIPANT_HIGH_ID)),
  CONSTRAINT SPLITO_CK_BILATERAL_AMOUNT CHECK (
    LOW_OWES_HIGH_MINOR_SIGNED BETWEEN -9999999999999999999 AND 9999999999999999999 AND
    LOW_OWES_HIGH_MINOR_SIGNED <> 0
  ),
  CONSTRAINT SPLITO_CK_BILATERAL_VERSION CHECK (PROJECTION_VERSION >= 0)
);

CREATE INDEX SPLITO_IX_BILATERAL_HIGH ON SPLITO_BILATERAL_PROJECTIONS (
  PARTICIPANT_HIGH_ID, CURRENCY_CODE, CONTEXT_ID
);

CREATE TABLE SPLITO_SETTLEMENTS (
  SETTLEMENT_ID RAW(16) NOT NULL,
  CONTEXT_ID RAW(16) NOT NULL,
  SENDER_PARTICIPANT_ID RAW(16) NOT NULL,
  RECIPIENT_PARTICIPANT_ID RAW(16) NOT NULL,
  CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  AMOUNT_MINOR NUMBER(19,0) NOT NULL,
  SETTLEMENT_DATE DATE NOT NULL,
  BUSINESS_TIMEZONE VARCHAR2(64 CHAR) NOT NULL,
  METHOD VARCHAR2(24 CHAR) NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'POSTED' NOT NULL,
  CURRENT_REVISION_ID RAW(16),
  PROVIDER_ATTEMPT_ID RAW(16),
  ASSERTION_FLAG CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DISPUTED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  VERSION_NO NUMBER(19,0) DEFAULT 1 NOT NULL,
  CREATED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_SETTLEMENTS PRIMARY KEY (SETTLEMENT_ID),
  CONSTRAINT SPLITO_FK_SETTLEMENT_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_SETTLEMENT_SENDER FOREIGN KEY (SENDER_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_SETTLEMENT_RECIPIENT FOREIGN KEY (RECIPIENT_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_SETTLEMENT_CURRENCY FOREIGN KEY (CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_FK_SETTLEMENT_CREATOR FOREIGN KEY (CREATED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_SETTLEMENT_PARTIES CHECK (SENDER_PARTICIPANT_ID <> RECIPIENT_PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_SETTLEMENT_AMOUNT CHECK (AMOUNT_MINOR BETWEEN 1 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_SETTLEMENT_DATE CHECK (SETTLEMENT_DATE = TRUNC(SETTLEMENT_DATE)),
  CONSTRAINT SPLITO_CK_SETTLEMENT_METHOD CHECK (METHOD IN ('CASH', 'BANK', 'UPI', 'CARD', 'OTHER', 'PROVIDER')),
  CONSTRAINT SPLITO_CK_SETTLEMENT_STATUS CHECK (STATUS IN ('POSTED', 'REVERSED', 'DISPUTED')),
  CONSTRAINT SPLITO_CK_SETTLEMENT_ASSERT CHECK (ASSERTION_FLAG IN ('Y', 'N')),
  CONSTRAINT SPLITO_CK_SETTLEMENT_DISPUTE CHECK (DISPUTED_FLAG IN ('Y', 'N')),
  CONSTRAINT SPLITO_CK_SETTLEMENT_VERSION CHECK (VERSION_NO >= 1)
);

CREATE INDEX SPLITO_IX_SETTLEMENT_CONTEXT ON SPLITO_SETTLEMENTS (
  CONTEXT_ID, CURRENCY_CODE, SETTLEMENT_DATE DESC, SETTLEMENT_ID
);
CREATE INDEX SPLITO_IX_SETTLEMENT_SENDER ON SPLITO_SETTLEMENTS (SENDER_PARTICIPANT_ID, CREATED_AT_UTC DESC);
CREATE INDEX SPLITO_IX_SETTLEMENT_RECIP ON SPLITO_SETTLEMENTS (RECIPIENT_PARTICIPANT_ID, CREATED_AT_UTC DESC);

CREATE TABLE SPLITO_SETTLEMENT_REVISIONS (
  SETTLEMENT_REVISION_ID RAW(16) NOT NULL,
  SETTLEMENT_ID RAW(16) NOT NULL,
  REVISION_NO NUMBER(19,0) NOT NULL,
  AMOUNT_MINOR NUMBER(19,0) NOT NULL,
  METHOD VARCHAR2(24 CHAR) NOT NULL,
  NOTE_TEXT VARCHAR2(2000 CHAR),
  CHANGE_TYPE VARCHAR2(10 CHAR) NOT NULL,
  CREATED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_SETTLEMENT_REVISIONS PRIMARY KEY (SETTLEMENT_REVISION_ID),
  CONSTRAINT SPLITO_UQ_SETTLEMENT_REV UNIQUE (SETTLEMENT_ID, REVISION_NO),
  CONSTRAINT SPLITO_FK_SETTLE_REV_SETTLEMENT FOREIGN KEY (SETTLEMENT_ID)
    REFERENCES SPLITO_SETTLEMENTS (SETTLEMENT_ID),
  CONSTRAINT SPLITO_FK_SETTLE_REV_CREATOR FOREIGN KEY (CREATED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_SETTLE_REV_NO CHECK (REVISION_NO >= 1),
  CONSTRAINT SPLITO_CK_SETTLE_REV_AMOUNT CHECK (AMOUNT_MINOR BETWEEN 1 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_SETTLE_REV_CHANGE CHECK (CHANGE_TYPE IN ('CREATE', 'EDIT', 'REVERSE'))
);

ALTER TABLE SPLITO_SETTLEMENTS ADD CONSTRAINT SPLITO_FK_SETTLEMENT_CURRENT_REV FOREIGN KEY (CURRENT_REVISION_ID)
  REFERENCES SPLITO_SETTLEMENT_REVISIONS (SETTLEMENT_REVISION_ID);

CREATE TABLE SPLITO_REFUNDS (
  REFUND_ID RAW(16) NOT NULL,
  ORIGINAL_EXPENSE_ID RAW(16) NOT NULL,
  CONTEXT_ID RAW(16) NOT NULL,
  CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  TOTAL_MINOR NUMBER(19,0) NOT NULL,
  REFUND_DATE DATE NOT NULL,
  BUSINESS_TIMEZONE VARCHAR2(64 CHAR) NOT NULL,
  STATUS VARCHAR2(10 CHAR) DEFAULT 'POSTED' NOT NULL,
  VERSION_NO NUMBER(19,0) DEFAULT 1 NOT NULL,
  CREATED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  VOIDED_AT_UTC TIMESTAMP(6),
  NOTE_TEXT VARCHAR2(2000 CHAR),
  CONSTRAINT SPLITO_PK_REFUNDS PRIMARY KEY (REFUND_ID),
  CONSTRAINT SPLITO_FK_REFUND_EXPENSE FOREIGN KEY (ORIGINAL_EXPENSE_ID) REFERENCES SPLITO_EXPENSES (EXPENSE_ID),
  CONSTRAINT SPLITO_FK_REFUND_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_REFUND_CURRENCY FOREIGN KEY (CURRENCY_CODE) REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_FK_REFUND_CREATOR FOREIGN KEY (CREATED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_REFUND_TOTAL CHECK (TOTAL_MINOR BETWEEN 1 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_REFUND_DATE CHECK (REFUND_DATE = TRUNC(REFUND_DATE)),
  CONSTRAINT SPLITO_CK_REFUND_STATUS CHECK (STATUS IN ('POSTED', 'VOIDED')),
  CONSTRAINT SPLITO_CK_REFUND_VERSION CHECK (VERSION_NO >= 1),
  CONSTRAINT SPLITO_CK_REFUND_VOIDED CHECK (
    (STATUS = 'POSTED' AND VOIDED_AT_UTC IS NULL) OR
    (STATUS = 'VOIDED' AND VOIDED_AT_UTC IS NOT NULL)
  )
);

CREATE INDEX SPLITO_IX_REFUND_ORIGINAL ON SPLITO_REFUNDS (ORIGINAL_EXPENSE_ID, STATUS, CREATED_AT_UTC);

CREATE TABLE SPLITO_REFUND_RECIPIENTS (
  REFUND_RECIPIENT_ID RAW(16) NOT NULL,
  REFUND_ID RAW(16) NOT NULL,
  PARTICIPANT_ID RAW(16) NOT NULL,
  RECEIVED_MINOR NUMBER(19,0) NOT NULL,
  ALLOCATION_ORDER NUMBER(10,0) NOT NULL,
  CONSTRAINT SPLITO_PK_REFUND_RECIPIENTS PRIMARY KEY (REFUND_RECIPIENT_ID),
  CONSTRAINT SPLITO_UQ_REFUND_RECIPIENT UNIQUE (REFUND_ID, PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_REFUND_RECIP_REFUND FOREIGN KEY (REFUND_ID) REFERENCES SPLITO_REFUNDS (REFUND_ID),
  CONSTRAINT SPLITO_FK_REFUND_RECIP_PART FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_REFUND_RECIP_AMOUNT CHECK (RECEIVED_MINOR BETWEEN 0 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_REFUND_RECIP_ORDER CHECK (ALLOCATION_ORDER >= 0)
);

CREATE TABLE SPLITO_REFUND_SHARES (
  REFUND_SHARE_ID RAW(16) NOT NULL,
  REFUND_ID RAW(16) NOT NULL,
  PARTICIPANT_ID RAW(16) NOT NULL,
  CREDIT_MINOR NUMBER(19,0) NOT NULL,
  ALLOCATION_ORDER NUMBER(10,0) NOT NULL,
  CONSTRAINT SPLITO_PK_REFUND_SHARES PRIMARY KEY (REFUND_SHARE_ID),
  CONSTRAINT SPLITO_UQ_REFUND_SHARE UNIQUE (REFUND_ID, PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_REFUND_SHARE_REFUND FOREIGN KEY (REFUND_ID) REFERENCES SPLITO_REFUNDS (REFUND_ID),
  CONSTRAINT SPLITO_FK_REFUND_SHARE_PART FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_REFUND_SHARE_AMOUNT CHECK (CREDIT_MINOR BETWEEN 0 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_REFUND_SHARE_ORDER CHECK (ALLOCATION_ORDER >= 0)
);

GRANT SELECT, INSERT, UPDATE ON SPLITO_EXPENSES TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_EXPENSE_REVISIONS TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_EXPENSE_PAYERS TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_EXPENSE_SHARES TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_EXPENSE_ITEMS TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_ITEM_ALLOCATIONS TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_LEDGER_BATCHES TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_LEDGER_POSTINGS TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_EXPENSE_OBLIGATIONS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SPLITO_BALANCE_PROJECTIONS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SPLITO_BILATERAL_PROJECTIONS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_SETTLEMENTS TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_SETTLEMENT_REVISIONS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_REFUNDS TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_REFUND_RECIPIENTS TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_REFUND_SHARES TO SPLITO_APP;
