CREATE TABLE SPLITO_IDEMPOTENCY_KEYS (
  IDEMPOTENCY_KEY_ID RAW(16) NOT NULL,
  ACTOR_PARTICIPANT_ID RAW(16) NOT NULL,
  OPERATION_KEY VARCHAR2(120 CHAR) NOT NULL,
  KEY_HASH RAW(32) NOT NULL,
  REQUEST_HASH RAW(32) NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'IN_PROGRESS' NOT NULL,
  HTTP_STATUS NUMBER(3,0),
  RESPONSE_BODY_JSON CLOB,
  RESOURCE_ID RAW(16),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  COMPLETED_AT_UTC TIMESTAMP(6),
  EXPIRES_AT_UTC TIMESTAMP(6) NOT NULL,
  CONSTRAINT SPLITO_PK_IDEMPOTENCY_KEYS PRIMARY KEY (IDEMPOTENCY_KEY_ID),
  CONSTRAINT SPLITO_UQ_IDEMPOTENCY_SCOPE UNIQUE (ACTOR_PARTICIPANT_ID, OPERATION_KEY, KEY_HASH),
  CONSTRAINT SPLITO_FK_IDEMPOTENCY_ACTOR FOREIGN KEY (ACTOR_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_IDEMPOTENCY_STATUS CHECK (STATUS IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')),
  CONSTRAINT SPLITO_CK_IDEMPOTENCY_HTTP CHECK (HTTP_STATUS IS NULL OR HTTP_STATUS BETWEEN 100 AND 599),
  CONSTRAINT SPLITO_CK_IDEMPOTENCY_JSON CHECK (RESPONSE_BODY_JSON IS NULL OR RESPONSE_BODY_JSON IS JSON),
  CONSTRAINT SPLITO_CK_IDEMPOTENCY_EXPIRY CHECK (EXPIRES_AT_UTC > CREATED_AT_UTC)
);

CREATE INDEX SPLITO_IX_IDEMPOTENCY_EXPIRY ON SPLITO_IDEMPOTENCY_KEYS (EXPIRES_AT_UTC, STATUS);

ALTER TABLE SPLITO_LEDGER_BATCHES ADD CONSTRAINT SPLITO_FK_LEDGER_IDEMPOTENCY
  FOREIGN KEY (IDEMPOTENCY_KEY_ID) REFERENCES SPLITO_IDEMPOTENCY_KEYS (IDEMPOTENCY_KEY_ID);

CREATE TABLE SPLITO_OUTBOX (
  OUTBOX_ID RAW(16) NOT NULL,
  EVENT_TYPE VARCHAR2(100 CHAR) NOT NULL,
  AGGREGATE_TYPE VARCHAR2(50 CHAR) NOT NULL,
  AGGREGATE_ID RAW(16) NOT NULL,
  PAYLOAD_JSON CLOB NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL,
  AVAILABLE_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  LEASED_UNTIL_UTC TIMESTAMP(6),
  LEASE_OWNER VARCHAR2(255 CHAR),
  ATTEMPTS NUMBER(5,0) DEFAULT 0 NOT NULL,
  LAST_ERROR VARCHAR2(4000 CHAR),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  PROCESSED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_OUTBOX PRIMARY KEY (OUTBOX_ID),
  CONSTRAINT SPLITO_CK_OUTBOX_PAYLOAD CHECK (PAYLOAD_JSON IS JSON),
  CONSTRAINT SPLITO_CK_OUTBOX_STATUS CHECK (STATUS IN ('PENDING', 'LEASED', 'RETRY', 'PROCESSED', 'DEAD')),
  CONSTRAINT SPLITO_CK_OUTBOX_ATTEMPTS CHECK (ATTEMPTS BETWEEN 0 AND 99999),
  CONSTRAINT SPLITO_CK_OUTBOX_LEASE CHECK (
    (STATUS = 'LEASED' AND LEASED_UNTIL_UTC IS NOT NULL AND LEASE_OWNER IS NOT NULL) OR
    STATUS <> 'LEASED'
  ),
  CONSTRAINT SPLITO_CK_OUTBOX_PROCESSED CHECK (
    (STATUS = 'PROCESSED' AND PROCESSED_AT_UTC IS NOT NULL) OR STATUS <> 'PROCESSED'
  )
);

CREATE INDEX SPLITO_IX_OUTBOX_AVAILABLE ON SPLITO_OUTBOX (STATUS, AVAILABLE_AT_UTC, OUTBOX_ID);
CREATE INDEX SPLITO_IX_OUTBOX_LEASE ON SPLITO_OUTBOX (LEASED_UNTIL_UTC, STATUS);
CREATE INDEX SPLITO_IX_OUTBOX_AGGREGATE ON SPLITO_OUTBOX (AGGREGATE_TYPE, AGGREGATE_ID, CREATED_AT_UTC);

CREATE TABLE SPLITO_DURABLE_JOBS (
  JOB_ID RAW(16) NOT NULL,
  JOB_TYPE VARCHAR2(80 CHAR) NOT NULL,
  DEDUPLICATION_KEY VARCHAR2(255 CHAR),
  PAYLOAD_JSON CLOB NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL,
  AVAILABLE_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  LEASED_UNTIL_UTC TIMESTAMP(6),
  LEASE_OWNER VARCHAR2(255 CHAR),
  ATTEMPTS NUMBER(5,0) DEFAULT 0 NOT NULL,
  MAX_ATTEMPTS NUMBER(5,0) DEFAULT 8 NOT NULL,
  LAST_ERROR VARCHAR2(4000 CHAR),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  COMPLETED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_DURABLE_JOBS PRIMARY KEY (JOB_ID),
  CONSTRAINT SPLITO_UQ_JOB_DEDUP UNIQUE (JOB_TYPE, DEDUPLICATION_KEY),
  CONSTRAINT SPLITO_CK_JOB_PAYLOAD CHECK (PAYLOAD_JSON IS JSON),
  CONSTRAINT SPLITO_CK_JOB_STATUS CHECK (STATUS IN ('PENDING', 'LEASED', 'RETRY', 'SUCCEEDED', 'DEAD')),
  CONSTRAINT SPLITO_CK_JOB_ATTEMPTS CHECK (ATTEMPTS BETWEEN 0 AND MAX_ATTEMPTS),
  CONSTRAINT SPLITO_CK_JOB_MAX_ATTEMPTS CHECK (MAX_ATTEMPTS BETWEEN 1 AND 100)
);

CREATE INDEX SPLITO_IX_JOB_AVAILABLE ON SPLITO_DURABLE_JOBS (STATUS, AVAILABLE_AT_UTC, JOB_ID);
CREATE INDEX SPLITO_IX_JOB_LEASE ON SPLITO_DURABLE_JOBS (LEASED_UNTIL_UTC, STATUS);

CREATE TABLE SPLITO_AUDIT_EVENTS (
  AUDIT_EVENT_ID RAW(16) NOT NULL,
  ACTOR_PARTICIPANT_ID RAW(16),
  ACTOR_USER_ID RAW(16),
  ACTION_KEY VARCHAR2(120 CHAR) NOT NULL,
  RESOURCE_TYPE VARCHAR2(80 CHAR) NOT NULL,
  RESOURCE_ID RAW(16),
  CONTEXT_ID RAW(16),
  REQUEST_ID VARCHAR2(100 CHAR) NOT NULL,
  IP_ADDRESS_HASH RAW(32),
  USER_AGENT_SUMMARY VARCHAR2(500 CHAR),
  METADATA_JSON CLOB DEFAULT '{}' NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_AUDIT_EVENTS PRIMARY KEY (AUDIT_EVENT_ID),
  CONSTRAINT SPLITO_FK_AUDIT_PARTICIPANT FOREIGN KEY (ACTOR_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_AUDIT_USER FOREIGN KEY (ACTOR_USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_FK_AUDIT_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_CK_AUDIT_METADATA CHECK (METADATA_JSON IS JSON)
);

CREATE INDEX SPLITO_IX_AUDIT_RESOURCE ON SPLITO_AUDIT_EVENTS (RESOURCE_TYPE, RESOURCE_ID, CREATED_AT_UTC);
CREATE INDEX SPLITO_IX_AUDIT_CONTEXT ON SPLITO_AUDIT_EVENTS (CONTEXT_ID, CREATED_AT_UTC, AUDIT_EVENT_ID);
CREATE INDEX SPLITO_IX_AUDIT_ACTOR ON SPLITO_AUDIT_EVENTS (ACTOR_USER_ID, CREATED_AT_UTC);

CREATE TABLE SPLITO_COMMENTS (
  COMMENT_ID RAW(16) NOT NULL,
  EXPENSE_ID RAW(16) NOT NULL,
  AUTHOR_PARTICIPANT_ID RAW(16) NOT NULL,
  BODY_TEXT VARCHAR2(4000 CHAR) NOT NULL,
  VERSION_NO NUMBER(19,0) DEFAULT 1 NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6),
  DELETED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_COMMENTS PRIMARY KEY (COMMENT_ID),
  CONSTRAINT SPLITO_FK_COMMENT_EXPENSE FOREIGN KEY (EXPENSE_ID) REFERENCES SPLITO_EXPENSES (EXPENSE_ID),
  CONSTRAINT SPLITO_FK_COMMENT_AUTHOR FOREIGN KEY (AUTHOR_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_COMMENT_VERSION CHECK (VERSION_NO >= 1)
);

CREATE INDEX SPLITO_IX_COMMENT_EXPENSE ON SPLITO_COMMENTS (EXPENSE_ID, CREATED_AT_UTC, COMMENT_ID);

CREATE TABLE SPLITO_DISPUTES (
  DISPUTE_ID RAW(16) NOT NULL,
  EXPENSE_ID RAW(16),
  SETTLEMENT_ID RAW(16),
  OPENED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'OPEN' NOT NULL,
  REASON_TEXT VARCHAR2(2000 CHAR) NOT NULL,
  RESOLUTION_TEXT VARCHAR2(2000 CHAR),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  RESOLVED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_DISPUTES PRIMARY KEY (DISPUTE_ID),
  CONSTRAINT SPLITO_FK_DISPUTE_EXPENSE FOREIGN KEY (EXPENSE_ID) REFERENCES SPLITO_EXPENSES (EXPENSE_ID),
  CONSTRAINT SPLITO_FK_DISPUTE_SETTLEMENT FOREIGN KEY (SETTLEMENT_ID)
    REFERENCES SPLITO_SETTLEMENTS (SETTLEMENT_ID),
  CONSTRAINT SPLITO_FK_DISPUTE_OPENER FOREIGN KEY (OPENED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_DISPUTE_RESOURCE CHECK (
    (EXPENSE_ID IS NOT NULL AND SETTLEMENT_ID IS NULL) OR
    (EXPENSE_ID IS NULL AND SETTLEMENT_ID IS NOT NULL)
  ),
  CONSTRAINT SPLITO_CK_DISPUTE_STATUS CHECK (STATUS IN ('OPEN', 'RESOLVED', 'REJECTED')),
  CONSTRAINT SPLITO_CK_DISPUTE_RESOLVED CHECK (
    (STATUS = 'OPEN' AND RESOLVED_AT_UTC IS NULL) OR
    (STATUS <> 'OPEN' AND RESOLVED_AT_UTC IS NOT NULL)
  )
);

CREATE TABLE SPLITO_ATTACHMENTS (
  ATTACHMENT_ID RAW(16) NOT NULL,
  EXPENSE_ID RAW(16) NOT NULL,
  UPLOADED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  STORAGE_PROVIDER VARCHAR2(30 CHAR) NOT NULL,
  STORAGE_KEY VARCHAR2(700 CHAR) NOT NULL,
  ORIGINAL_FILENAME VARCHAR2(255 CHAR) NOT NULL,
  MEDIA_TYPE VARCHAR2(120 CHAR) NOT NULL,
  BYTE_SIZE NUMBER(19,0) NOT NULL,
  SHA256_HASH RAW(32) NOT NULL,
  PAGE_COUNT NUMBER(5,0),
  SCAN_STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  DELETED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_ATTACHMENTS PRIMARY KEY (ATTACHMENT_ID),
  CONSTRAINT SPLITO_UQ_ATTACHMENT_STORAGE UNIQUE (STORAGE_PROVIDER, STORAGE_KEY),
  CONSTRAINT SPLITO_FK_ATTACHMENT_EXPENSE FOREIGN KEY (EXPENSE_ID) REFERENCES SPLITO_EXPENSES (EXPENSE_ID),
  CONSTRAINT SPLITO_FK_ATTACHMENT_UPLOADER FOREIGN KEY (UPLOADED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_ATTACHMENT_SIZE CHECK (BYTE_SIZE BETWEEN 1 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_ATTACHMENT_PAGES CHECK (PAGE_COUNT IS NULL OR PAGE_COUNT BETWEEN 1 AND 100),
  CONSTRAINT SPLITO_CK_ATTACHMENT_SCAN CHECK (SCAN_STATUS IN ('PENDING', 'CLEAN', 'REJECTED', 'FAILED'))
);

CREATE INDEX SPLITO_IX_ATTACHMENT_EXPENSE ON SPLITO_ATTACHMENTS (EXPENSE_ID, DELETED_AT_UTC, CREATED_AT_UTC);

CREATE TABLE SPLITO_OCR_RESULTS (
  OCR_RESULT_ID RAW(16) NOT NULL,
  ATTACHMENT_ID RAW(16) NOT NULL,
  PROVIDER_KEY VARCHAR2(80 CHAR) NOT NULL,
  PROVIDER_VERSION VARCHAR2(80 CHAR),
  STATUS VARCHAR2(12 CHAR) NOT NULL,
  EXTRACTED_JSON CLOB,
  ERROR_SUMMARY VARCHAR2(1000 CHAR),
  STARTED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  COMPLETED_AT_UTC TIMESTAMP(6),
  CONFIRMED_BY_PARTICIPANT_ID RAW(16),
  CONFIRMED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_OCR_RESULTS PRIMARY KEY (OCR_RESULT_ID),
  CONSTRAINT SPLITO_FK_OCR_ATTACHMENT FOREIGN KEY (ATTACHMENT_ID) REFERENCES SPLITO_ATTACHMENTS (ATTACHMENT_ID),
  CONSTRAINT SPLITO_FK_OCR_CONFIRMER FOREIGN KEY (CONFIRMED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_OCR_STATUS CHECK (STATUS IN ('PENDING', 'PROCESSING', 'READY', 'FAILED', 'CONFIRMED')),
  CONSTRAINT SPLITO_CK_OCR_JSON CHECK (EXTRACTED_JSON IS NULL OR EXTRACTED_JSON IS JSON)
);

CREATE INDEX SPLITO_IX_OCR_ATTACHMENT ON SPLITO_OCR_RESULTS (ATTACHMENT_ID, STARTED_AT_UTC DESC);

CREATE TABLE SPLITO_PAYMENT_ATTEMPTS (
  PAYMENT_ATTEMPT_ID RAW(16) NOT NULL,
  PROVIDER_KEY VARCHAR2(80 CHAR) NOT NULL,
  PROVIDER_REFERENCE VARCHAR2(255 CHAR),
  CONTEXT_ID RAW(16) NOT NULL,
  SENDER_PARTICIPANT_ID RAW(16) NOT NULL,
  RECIPIENT_PARTICIPANT_ID RAW(16) NOT NULL,
  CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  AMOUNT_MINOR NUMBER(19,0) NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL,
  REQUEST_JSON CLOB NOT NULL,
  RESPONSE_JSON CLOB,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  EXPIRES_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_PAYMENT_ATTEMPTS PRIMARY KEY (PAYMENT_ATTEMPT_ID),
  CONSTRAINT SPLITO_UQ_PAYMENT_PROVIDER_REF UNIQUE (PROVIDER_KEY, PROVIDER_REFERENCE),
  CONSTRAINT SPLITO_FK_PAYMENT_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_PAYMENT_SENDER FOREIGN KEY (SENDER_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_PAYMENT_RECIPIENT FOREIGN KEY (RECIPIENT_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_FK_PAYMENT_CURRENCY FOREIGN KEY (CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_CK_PAYMENT_PARTIES CHECK (SENDER_PARTICIPANT_ID <> RECIPIENT_PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_PAYMENT_AMOUNT CHECK (AMOUNT_MINOR BETWEEN 1 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_PAYMENT_STATUS CHECK (STATUS IN ('PENDING', 'SUCCESSFUL', 'FAILED', 'CANCELLED', 'EXPIRED', 'REVERSED')),
  CONSTRAINT SPLITO_CK_PAYMENT_REQUEST CHECK (REQUEST_JSON IS JSON),
  CONSTRAINT SPLITO_CK_PAYMENT_RESPONSE CHECK (RESPONSE_JSON IS NULL OR RESPONSE_JSON IS JSON)
);

ALTER TABLE SPLITO_SETTLEMENTS ADD CONSTRAINT SPLITO_FK_SETTLEMENT_PROVIDER_ATTEMPT
  FOREIGN KEY (PROVIDER_ATTEMPT_ID) REFERENCES SPLITO_PAYMENT_ATTEMPTS (PAYMENT_ATTEMPT_ID);

CREATE TABLE SPLITO_WEBHOOK_RECEIPTS (
  WEBHOOK_RECEIPT_ID RAW(16) NOT NULL,
  PROVIDER_KEY VARCHAR2(80 CHAR) NOT NULL,
  PROVIDER_EVENT_ID VARCHAR2(255 CHAR) NOT NULL,
  PAYLOAD_SHA256 RAW(32) NOT NULL,
  SIGNATURE_VALID_FLAG CHAR(1 CHAR) NOT NULL,
  EVENT_TIMESTAMP_UTC TIMESTAMP(6),
  RECEIVED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  PROCESSED_AT_UTC TIMESTAMP(6),
  STATUS VARCHAR2(12 CHAR) DEFAULT 'RECEIVED' NOT NULL,
  FAILURE_SUMMARY VARCHAR2(1000 CHAR),
  CONSTRAINT SPLITO_PK_WEBHOOK_RECEIPTS PRIMARY KEY (WEBHOOK_RECEIPT_ID),
  CONSTRAINT SPLITO_UQ_WEBHOOK_EVENT UNIQUE (PROVIDER_KEY, PROVIDER_EVENT_ID),
  CONSTRAINT SPLITO_CK_WEBHOOK_SIGNATURE CHECK (SIGNATURE_VALID_FLAG IN ('Y', 'N')),
  CONSTRAINT SPLITO_CK_WEBHOOK_STATUS CHECK (STATUS IN ('RECEIVED', 'PROCESSED', 'REJECTED', 'FAILED'))
);

CREATE INDEX SPLITO_IX_WEBHOOK_RECEIVED ON SPLITO_WEBHOOK_RECEIPTS (PROVIDER_KEY, RECEIVED_AT_UTC);

CREATE TABLE SPLITO_RECURRENCE_TEMPLATES (
  RECURRENCE_TEMPLATE_ID RAW(16) NOT NULL,
  CONTEXT_ID RAW(16) NOT NULL,
  CREATED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  TEMPLATE_JSON CLOB NOT NULL,
  FREQUENCY VARCHAR2(12 CHAR) NOT NULL,
  INTERVAL_NO NUMBER(5,0) DEFAULT 1 NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  OCCURRENCE_LIMIT NUMBER(10,0),
  TIMEZONE_NAME VARCHAR2(64 CHAR) NOT NULL,
  LOCAL_TIME_HHMM VARCHAR2(5 CHAR) NOT NULL,
  NEXT_RUN_AT_UTC TIMESTAMP(6) NOT NULL,
  GENERATED_COUNT NUMBER(10,0) DEFAULT 0 NOT NULL,
  STATUS VARCHAR2(10 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  VERSION_NO NUMBER(19,0) DEFAULT 1 NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_RECURRENCE_TEMPLATES PRIMARY KEY (RECURRENCE_TEMPLATE_ID),
  CONSTRAINT SPLITO_FK_RECURRENCE_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_RECURRENCE_CREATOR FOREIGN KEY (CREATED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_RECURRENCE_JSON CHECK (TEMPLATE_JSON IS JSON),
  CONSTRAINT SPLITO_CK_RECURRENCE_FREQ CHECK (FREQUENCY IN ('DAILY', 'WEEKLY', 'FORTNIGHTLY', 'MONTHLY', 'YEARLY')),
  CONSTRAINT SPLITO_CK_RECURRENCE_INTERVAL CHECK (INTERVAL_NO BETWEEN 1 AND 1000),
  CONSTRAINT SPLITO_CK_RECURRENCE_DATES CHECK (
    START_DATE = TRUNC(START_DATE) AND (END_DATE IS NULL OR (END_DATE = TRUNC(END_DATE) AND END_DATE >= START_DATE))
  ),
  CONSTRAINT SPLITO_CK_RECURRENCE_LIMIT CHECK (OCCURRENCE_LIMIT IS NULL OR OCCURRENCE_LIMIT >= 1),
  CONSTRAINT SPLITO_CK_RECURRENCE_TIME CHECK (REGEXP_LIKE(LOCAL_TIME_HHMM, '^(?:[01][0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT SPLITO_CK_RECURRENCE_STATUS CHECK (STATUS IN ('ACTIVE', 'PAUSED', 'CANCELLED', 'COMPLETED', 'INVALID')),
  CONSTRAINT SPLITO_CK_RECURRENCE_COUNT CHECK (GENERATED_COUNT >= 0),
  CONSTRAINT SPLITO_CK_RECURRENCE_VERSION CHECK (VERSION_NO >= 1)
);

CREATE INDEX SPLITO_IX_RECURRENCE_DUE ON SPLITO_RECURRENCE_TEMPLATES (STATUS, NEXT_RUN_AT_UTC, RECURRENCE_TEMPLATE_ID);

CREATE TABLE SPLITO_RECURRENCE_OCCURRENCES (
  RECURRENCE_OCCURRENCE_ID RAW(16) NOT NULL,
  RECURRENCE_TEMPLATE_ID RAW(16) NOT NULL,
  OCCURRENCE_LOCAL_DATE DATE NOT NULL,
  EXPENSE_ID RAW(16),
  STATUS VARCHAR2(12 CHAR) NOT NULL,
  ATTEMPTS NUMBER(5,0) DEFAULT 0 NOT NULL,
  ERROR_SUMMARY VARCHAR2(1000 CHAR),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  COMPLETED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_RECURRENCE_OCCURRENCES PRIMARY KEY (RECURRENCE_OCCURRENCE_ID),
  CONSTRAINT SPLITO_UQ_RECURRENCE_OCC UNIQUE (RECURRENCE_TEMPLATE_ID, OCCURRENCE_LOCAL_DATE),
  CONSTRAINT SPLITO_FK_OCCURRENCE_TEMPLATE FOREIGN KEY (RECURRENCE_TEMPLATE_ID)
    REFERENCES SPLITO_RECURRENCE_TEMPLATES (RECURRENCE_TEMPLATE_ID),
  CONSTRAINT SPLITO_FK_OCCURRENCE_EXPENSE FOREIGN KEY (EXPENSE_ID) REFERENCES SPLITO_EXPENSES (EXPENSE_ID),
  CONSTRAINT SPLITO_CK_OCCURRENCE_DATE CHECK (OCCURRENCE_LOCAL_DATE = TRUNC(OCCURRENCE_LOCAL_DATE)),
  CONSTRAINT SPLITO_CK_OCCURRENCE_STATUS CHECK (STATUS IN ('PENDING', 'GENERATED', 'SKIPPED', 'FAILED')),
  CONSTRAINT SPLITO_CK_OCCURRENCE_ATTEMPTS CHECK (ATTEMPTS BETWEEN 0 AND 99999)
);

ALTER TABLE SPLITO_EXPENSES ADD RECURRENCE_OCCURRENCE_ID RAW(16);
ALTER TABLE SPLITO_EXPENSES ADD CONSTRAINT SPLITO_UQ_EXPENSE_RECURRENCE UNIQUE (RECURRENCE_OCCURRENCE_ID);
ALTER TABLE SPLITO_EXPENSES ADD CONSTRAINT SPLITO_FK_EXPENSE_RECURRENCE FOREIGN KEY (RECURRENCE_OCCURRENCE_ID)
  REFERENCES SPLITO_RECURRENCE_OCCURRENCES (RECURRENCE_OCCURRENCE_ID);

CREATE TABLE SPLITO_FX_RATES (
  FX_RATE_ID RAW(16) NOT NULL,
  BASE_CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  QUOTE_CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  RATE_DECIMAL VARCHAR2(100 CHAR) NOT NULL,
  PROVIDER_KEY VARCHAR2(80 CHAR) NOT NULL,
  PROVIDER_RATE_ID VARCHAR2(255 CHAR),
  QUOTED_AT_UTC TIMESTAMP(6) NOT NULL,
  EXPIRES_AT_UTC TIMESTAMP(6),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_FX_RATES PRIMARY KEY (FX_RATE_ID),
  CONSTRAINT SPLITO_FK_FX_BASE FOREIGN KEY (BASE_CURRENCY_CODE) REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_FK_FX_QUOTE FOREIGN KEY (QUOTE_CURRENCY_CODE) REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_CK_FX_PAIR CHECK (BASE_CURRENCY_CODE <> QUOTE_CURRENCY_CODE),
  CONSTRAINT SPLITO_CK_FX_RATE CHECK (REGEXP_LIKE(RATE_DECIMAL, '^(?:0|[1-9][0-9]*)(?:\.[0-9]{1,30})?$') AND RATE_DECIMAL <> '0')
);

CREATE INDEX SPLITO_IX_FX_PAIR_TIME ON SPLITO_FX_RATES (
  BASE_CURRENCY_CODE, QUOTE_CURRENCY_CODE, QUOTED_AT_UTC DESC, FX_RATE_ID
);

CREATE TABLE SPLITO_CURRENCY_CONVERSIONS (
  CONVERSION_ID RAW(16) NOT NULL,
  CONTEXT_ID RAW(16) NOT NULL,
  SOURCE_CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  TARGET_CURRENCY_CODE CHAR(3 CHAR) NOT NULL,
  SOURCE_TOTAL_MINOR NUMBER(19,0) NOT NULL,
  TARGET_TOTAL_MINOR NUMBER(19,0) NOT NULL,
  RATE_DECIMAL VARCHAR2(100 CHAR) NOT NULL,
  RATE_PROVIDER_KEY VARCHAR2(80 CHAR) NOT NULL,
  RATE_QUOTED_AT_UTC TIMESTAMP(6) NOT NULL,
  ROUNDING_POLICY VARCHAR2(40 CHAR) NOT NULL,
  SOURCE_BATCH_ID RAW(16),
  TARGET_BATCH_ID RAW(16),
  REVERSES_CONVERSION_ID RAW(16),
  STATUS VARCHAR2(10 CHAR) DEFAULT 'POSTED' NOT NULL,
  VERSION_NO NUMBER(19,0) DEFAULT 1 NOT NULL,
  CREATED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_CURRENCY_CONVERSIONS PRIMARY KEY (CONVERSION_ID),
  CONSTRAINT SPLITO_UQ_CONVERSION_REVERSAL UNIQUE (REVERSES_CONVERSION_ID),
  CONSTRAINT SPLITO_FK_CONVERSION_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES SPLITO_CONTEXTS (CONTEXT_ID),
  CONSTRAINT SPLITO_FK_CONVERSION_SOURCE_CUR FOREIGN KEY (SOURCE_CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_FK_CONVERSION_TARGET_CUR FOREIGN KEY (TARGET_CURRENCY_CODE)
    REFERENCES SPLITO_CURRENCIES (CURRENCY_CODE),
  CONSTRAINT SPLITO_FK_CONVERSION_SOURCE_BATCH FOREIGN KEY (SOURCE_BATCH_ID)
    REFERENCES SPLITO_LEDGER_BATCHES (BATCH_ID),
  CONSTRAINT SPLITO_FK_CONVERSION_TARGET_BATCH FOREIGN KEY (TARGET_BATCH_ID)
    REFERENCES SPLITO_LEDGER_BATCHES (BATCH_ID),
  CONSTRAINT SPLITO_FK_CONVERSION_REVERSES FOREIGN KEY (REVERSES_CONVERSION_ID)
    REFERENCES SPLITO_CURRENCY_CONVERSIONS (CONVERSION_ID),
  CONSTRAINT SPLITO_FK_CONVERSION_CREATOR FOREIGN KEY (CREATED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_CONVERSION_PAIR CHECK (SOURCE_CURRENCY_CODE <> TARGET_CURRENCY_CODE),
  CONSTRAINT SPLITO_CK_CONVERSION_SOURCE CHECK (SOURCE_TOTAL_MINOR BETWEEN 1 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_CONVERSION_TARGET CHECK (TARGET_TOTAL_MINOR BETWEEN 1 AND 9999999999999999999),
  CONSTRAINT SPLITO_CK_CONVERSION_RATE CHECK (REGEXP_LIKE(RATE_DECIMAL, '^(?:0|[1-9][0-9]*)(?:\.[0-9]{1,30})?$') AND RATE_DECIMAL <> '0'),
  CONSTRAINT SPLITO_CK_CONVERSION_STATUS CHECK (STATUS IN ('POSTED', 'REVERSED')),
  CONSTRAINT SPLITO_CK_CONVERSION_VERSION CHECK (VERSION_NO >= 1)
);

CREATE TABLE SPLITO_IMPORT_BATCHES (
  IMPORT_BATCH_ID RAW(16) NOT NULL,
  OWNER_PARTICIPANT_ID RAW(16) NOT NULL,
  ORIGINAL_FILENAME VARCHAR2(255 CHAR) NOT NULL,
  FILE_SHA256 RAW(32) NOT NULL,
  MAPPING_JSON CLOB NOT NULL,
  STATUS VARCHAR2(14 CHAR) DEFAULT 'PREVIEW' NOT NULL,
  TOTAL_ROWS NUMBER(10,0) DEFAULT 0 NOT NULL,
  VALID_ROWS NUMBER(10,0) DEFAULT 0 NOT NULL,
  IMPORTED_ROWS NUMBER(10,0) DEFAULT 0 NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  COMPLETED_AT_UTC TIMESTAMP(6),
  REVERSED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_IMPORT_BATCHES PRIMARY KEY (IMPORT_BATCH_ID),
  CONSTRAINT SPLITO_FK_IMPORT_OWNER FOREIGN KEY (OWNER_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_IMPORT_MAPPING CHECK (MAPPING_JSON IS JSON),
  CONSTRAINT SPLITO_CK_IMPORT_STATUS CHECK (STATUS IN ('PREVIEW', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED')),
  CONSTRAINT SPLITO_CK_IMPORT_COUNTS CHECK (
    TOTAL_ROWS >= 0 AND VALID_ROWS >= 0 AND IMPORTED_ROWS >= 0 AND
    VALID_ROWS <= TOTAL_ROWS AND IMPORTED_ROWS <= VALID_ROWS
  )
);

CREATE TABLE SPLITO_IMPORT_ROWS (
  IMPORT_ROW_ID RAW(16) NOT NULL,
  IMPORT_BATCH_ID RAW(16) NOT NULL,
  ROW_NUMBER_NO NUMBER(10,0) NOT NULL,
  SOURCE_ROW_JSON CLOB NOT NULL,
  NORMALIZED_ROW_JSON CLOB,
  DUPLICATE_FINGERPRINT RAW(32),
  STATUS VARCHAR2(12 CHAR) NOT NULL,
  ERROR_JSON CLOB,
  CREATED_EXPENSE_ID RAW(16),
  FORMULA_NEUTRALIZED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  CONSTRAINT SPLITO_PK_IMPORT_ROWS PRIMARY KEY (IMPORT_ROW_ID),
  CONSTRAINT SPLITO_UQ_IMPORT_ROW_NO UNIQUE (IMPORT_BATCH_ID, ROW_NUMBER_NO),
  CONSTRAINT SPLITO_FK_IMPORT_ROW_BATCH FOREIGN KEY (IMPORT_BATCH_ID)
    REFERENCES SPLITO_IMPORT_BATCHES (IMPORT_BATCH_ID),
  CONSTRAINT SPLITO_FK_IMPORT_ROW_EXPENSE FOREIGN KEY (CREATED_EXPENSE_ID) REFERENCES SPLITO_EXPENSES (EXPENSE_ID),
  CONSTRAINT SPLITO_CK_IMPORT_SOURCE CHECK (SOURCE_ROW_JSON IS JSON),
  CONSTRAINT SPLITO_CK_IMPORT_NORMALIZED CHECK (NORMALIZED_ROW_JSON IS NULL OR NORMALIZED_ROW_JSON IS JSON),
  CONSTRAINT SPLITO_CK_IMPORT_ERROR CHECK (ERROR_JSON IS NULL OR ERROR_JSON IS JSON),
  CONSTRAINT SPLITO_CK_IMPORT_ROW_STATUS CHECK (STATUS IN ('VALID', 'INVALID', 'DUPLICATE', 'IMPORTED', 'FAILED')),
  CONSTRAINT SPLITO_CK_IMPORT_ROW_NO CHECK (ROW_NUMBER_NO >= 1),
  CONSTRAINT SPLITO_CK_IMPORT_FORMULA CHECK (FORMULA_NEUTRALIZED_FLAG IN ('Y', 'N'))
);

CREATE INDEX SPLITO_IX_IMPORT_ROW_BATCH ON SPLITO_IMPORT_ROWS (IMPORT_BATCH_ID, STATUS, ROW_NUMBER_NO);

CREATE TABLE SPLITO_EXPORT_JOBS (
  EXPORT_JOB_ID RAW(16) NOT NULL,
  REQUESTED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  EXPORT_TYPE VARCHAR2(24 CHAR) NOT NULL,
  FILTERS_JSON CLOB DEFAULT '{}' NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL,
  STORAGE_KEY VARCHAR2(700 CHAR),
  BYTE_SIZE NUMBER(19,0),
  SHA256_HASH RAW(32),
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  COMPLETED_AT_UTC TIMESTAMP(6),
  EXPIRES_AT_UTC TIMESTAMP(6),
  ERROR_SUMMARY VARCHAR2(1000 CHAR),
  CONSTRAINT SPLITO_PK_EXPORT_JOBS PRIMARY KEY (EXPORT_JOB_ID),
  CONSTRAINT SPLITO_FK_EXPORT_REQUESTER FOREIGN KEY (REQUESTED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_EXPORT_TYPE CHECK (EXPORT_TYPE IN ('EXPENSE_CSV', 'BALANCE_CSV', 'SETTLEMENT_CSV', 'ACCOUNT_JSON', 'GROUP_PDF')),
  CONSTRAINT SPLITO_CK_EXPORT_FILTERS CHECK (FILTERS_JSON IS JSON),
  CONSTRAINT SPLITO_CK_EXPORT_STATUS CHECK (STATUS IN ('PENDING', 'PROCESSING', 'READY', 'FAILED', 'EXPIRED')),
  CONSTRAINT SPLITO_CK_EXPORT_SIZE CHECK (BYTE_SIZE IS NULL OR BYTE_SIZE BETWEEN 0 AND 9999999999999999999)
);

CREATE INDEX SPLITO_IX_EXPORT_REQUESTER ON SPLITO_EXPORT_JOBS (
  REQUESTED_BY_PARTICIPANT_ID, CREATED_AT_UTC DESC, EXPORT_JOB_ID
);

CREATE TABLE SPLITO_NOTIFICATIONS (
  NOTIFICATION_ID RAW(16) NOT NULL,
  USER_ID RAW(16) NOT NULL,
  NOTIFICATION_TYPE VARCHAR2(80 CHAR) NOT NULL,
  RESOURCE_TYPE VARCHAR2(50 CHAR),
  RESOURCE_ID RAW(16),
  PAYLOAD_JSON CLOB NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  READ_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_NOTIFICATIONS PRIMARY KEY (NOTIFICATION_ID),
  CONSTRAINT SPLITO_FK_NOTIFICATION_USER FOREIGN KEY (USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_CK_NOTIFICATION_PAYLOAD CHECK (PAYLOAD_JSON IS JSON)
);

CREATE INDEX SPLITO_IX_NOTIFICATION_USER ON SPLITO_NOTIFICATIONS (USER_ID, READ_AT_UTC, CREATED_AT_UTC DESC);

CREATE TABLE SPLITO_SYNC_MUTATIONS (
  SYNC_MUTATION_ID RAW(16) NOT NULL,
  USER_ID RAW(16) NOT NULL,
  CLIENT_ID RAW(16) NOT NULL,
  CLIENT_SEQUENCE NUMBER(19,0) NOT NULL,
  IDEMPOTENCY_KEY_ID RAW(16) NOT NULL,
  DEPENDS_ON_MUTATION_ID RAW(16),
  OPERATION_KEY VARCHAR2(120 CHAR) NOT NULL,
  RESOURCE_ID RAW(16),
  BASE_VERSION NUMBER(19,0),
  STATUS VARCHAR2(12 CHAR) DEFAULT 'RECEIVED' NOT NULL,
  RESULT_JSON CLOB,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  COMPLETED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_SYNC_MUTATIONS PRIMARY KEY (SYNC_MUTATION_ID),
  CONSTRAINT SPLITO_UQ_SYNC_CLIENT_SEQ UNIQUE (USER_ID, CLIENT_ID, CLIENT_SEQUENCE),
  CONSTRAINT SPLITO_FK_SYNC_USER FOREIGN KEY (USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_FK_SYNC_IDEMPOTENCY FOREIGN KEY (IDEMPOTENCY_KEY_ID)
    REFERENCES SPLITO_IDEMPOTENCY_KEYS (IDEMPOTENCY_KEY_ID),
  CONSTRAINT SPLITO_FK_SYNC_DEPENDENCY FOREIGN KEY (DEPENDS_ON_MUTATION_ID)
    REFERENCES SPLITO_SYNC_MUTATIONS (SYNC_MUTATION_ID),
  CONSTRAINT SPLITO_CK_SYNC_SEQUENCE CHECK (CLIENT_SEQUENCE >= 0),
  CONSTRAINT SPLITO_CK_SYNC_BASE_VERSION CHECK (BASE_VERSION IS NULL OR BASE_VERSION >= 1),
  CONSTRAINT SPLITO_CK_SYNC_STATUS CHECK (STATUS IN ('RECEIVED', 'APPLIED', 'CONFLICT', 'REJECTED', 'FAILED')),
  CONSTRAINT SPLITO_CK_SYNC_RESULT CHECK (RESULT_JSON IS NULL OR RESULT_JSON IS JSON)
);

CREATE TABLE SPLITO_ENTITLEMENTS (
  ENTITLEMENT_ID RAW(16) NOT NULL,
  USER_ID RAW(16) NOT NULL,
  ENTITLEMENT_KEY VARCHAR2(100 CHAR) NOT NULL,
  STATUS VARCHAR2(10 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  SOURCE VARCHAR2(30 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  STARTS_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  ENDS_AT_UTC TIMESTAMP(6),
  METADATA_JSON CLOB DEFAULT '{}' NOT NULL,
  CONSTRAINT SPLITO_PK_ENTITLEMENTS PRIMARY KEY (ENTITLEMENT_ID),
  CONSTRAINT SPLITO_UQ_ENTITLEMENT UNIQUE (USER_ID, ENTITLEMENT_KEY, STARTS_AT_UTC),
  CONSTRAINT SPLITO_FK_ENTITLEMENT_USER FOREIGN KEY (USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_CK_ENTITLEMENT_STATUS CHECK (STATUS IN ('ACTIVE', 'EXPIRED', 'REVOKED')),
  CONSTRAINT SPLITO_CK_ENTITLEMENT_DATES CHECK (ENDS_AT_UTC IS NULL OR ENDS_AT_UTC > STARTS_AT_UTC),
  CONSTRAINT SPLITO_CK_ENTITLEMENT_METADATA CHECK (METADATA_JSON IS JSON)
);

GRANT SELECT, INSERT, UPDATE ON SPLITO_IDEMPOTENCY_KEYS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_OUTBOX TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_DURABLE_JOBS TO SPLITO_APP;
GRANT SELECT, INSERT ON SPLITO_AUDIT_EVENTS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_COMMENTS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_DISPUTES TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_ATTACHMENTS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_OCR_RESULTS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_PAYMENT_ATTEMPTS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_WEBHOOK_RECEIPTS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_RECURRENCE_TEMPLATES TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_RECURRENCE_OCCURRENCES TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_FX_RATES TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_CURRENCY_CONVERSIONS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_IMPORT_BATCHES TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_IMPORT_ROWS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_EXPORT_JOBS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_NOTIFICATIONS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_SYNC_MUTATIONS TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_ENTITLEMENTS TO SPLITO_APP;
