ALTER TABLE SPLITO_USERS MODIFY (EMAIL_NORMALIZED NULL);

ALTER TABLE SPLITO_USERS ADD MOBILE_E164 VARCHAR2(16 CHAR);

ALTER TABLE SPLITO_USERS ADD MOBILE_VERIFIED_AT_UTC TIMESTAMP(6);

ALTER TABLE SPLITO_USERS ADD CONSTRAINT SPLITO_UQ_USERS_MOBILE UNIQUE (MOBILE_E164);

ALTER TABLE SPLITO_USERS ADD CONSTRAINT SPLITO_CK_USERS_MOBILE CHECK (
  MOBILE_E164 IS NULL OR REGEXP_LIKE(MOBILE_E164, '^\+[1-9][0-9]{7,14}$')
);

ALTER TABLE SPLITO_USERS ADD CONSTRAINT SPLITO_CK_USERS_MOBILE_VERIFIED CHECK (
  (MOBILE_E164 IS NULL AND MOBILE_VERIFIED_AT_UTC IS NULL) OR
  (MOBILE_E164 IS NOT NULL AND MOBILE_VERIFIED_AT_UTC IS NOT NULL)
);

ALTER TABLE SPLITO_USERS ADD CONSTRAINT SPLITO_CK_USERS_IDENTITY CHECK (
  EMAIL_NORMALIZED IS NOT NULL OR MOBILE_E164 IS NOT NULL
);

CREATE TABLE SPLITO_MOBILE_OTP_CHALLENGES (
  OTP_CHALLENGE_ID RAW(16) NOT NULL,
  MOBILE_E164 VARCHAR2(16 CHAR) NOT NULL,
  PURPOSE VARCHAR2(16 CHAR) DEFAULT 'LOGIN' NOT NULL,
  OTP_HASH RAW(32) NOT NULL,
  REQUEST_IP_HASH RAW(32) NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL,
  ATTEMPT_COUNT NUMBER(3,0) DEFAULT 0 NOT NULL,
  MAX_ATTEMPTS NUMBER(3,0) DEFAULT 5 NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  EXPIRES_AT_UTC TIMESTAMP(6) NOT NULL,
  LAST_ATTEMPT_AT_UTC TIMESTAMP(6),
  CONSUMED_AT_UTC TIMESTAMP(6),
  TERMINAL_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_MOBILE_OTP PRIMARY KEY (OTP_CHALLENGE_ID),
  CONSTRAINT SPLITO_CK_MOBILE_OTP_PHONE CHECK (
    REGEXP_LIKE(MOBILE_E164, '^\+[1-9][0-9]{7,14}$')
  ),
  CONSTRAINT SPLITO_CK_MOBILE_OTP_PURPOSE CHECK (PURPOSE = 'LOGIN'),
  CONSTRAINT SPLITO_CK_MOBILE_OTP_STATUS CHECK (
    STATUS IN ('PENDING', 'VERIFIED', 'EXPIRED', 'LOCKED', 'SUPERSEDED')
  ),
  CONSTRAINT SPLITO_CK_MOBILE_OTP_TRIES CHECK (
    ATTEMPT_COUNT BETWEEN 0 AND 5 AND MAX_ATTEMPTS = 5 AND
    (STATUS <> 'PENDING' OR ATTEMPT_COUNT < MAX_ATTEMPTS) AND
    (STATUS <> 'LOCKED' OR ATTEMPT_COUNT = MAX_ATTEMPTS)
  ),
  CONSTRAINT SPLITO_CK_MOBILE_OTP_EXPIRY CHECK (EXPIRES_AT_UTC > CREATED_AT_UTC),
  CONSTRAINT SPLITO_CK_MOBILE_OTP_TIME CHECK (
    (LAST_ATTEMPT_AT_UTC IS NULL OR LAST_ATTEMPT_AT_UTC >= CREATED_AT_UTC) AND
    (TERMINAL_AT_UTC IS NULL OR TERMINAL_AT_UTC >= CREATED_AT_UTC) AND
    (CONSUMED_AT_UTC IS NULL OR
      (CONSUMED_AT_UTC >= CREATED_AT_UTC AND CONSUMED_AT_UTC <= EXPIRES_AT_UTC))
  ),
  CONSTRAINT SPLITO_CK_MOBILE_OTP_TERMINAL CHECK (
    (STATUS = 'PENDING' AND CONSUMED_AT_UTC IS NULL AND TERMINAL_AT_UTC IS NULL) OR
    (STATUS = 'VERIFIED' AND CONSUMED_AT_UTC IS NOT NULL AND TERMINAL_AT_UTC IS NOT NULL) OR
    (STATUS IN ('EXPIRED', 'LOCKED', 'SUPERSEDED') AND
      CONSUMED_AT_UTC IS NULL AND TERMINAL_AT_UTC IS NOT NULL)
  )
);

CREATE UNIQUE INDEX SPLITO_UQ_PENDING_MOBILE_OTP ON SPLITO_MOBILE_OTP_CHALLENGES (
  CASE WHEN STATUS = 'PENDING' THEN MOBILE_E164 END,
  CASE WHEN STATUS = 'PENDING' THEN PURPOSE END
);

CREATE INDEX SPLITO_IX_MOBILE_OTP_PHONE ON SPLITO_MOBILE_OTP_CHALLENGES (
  MOBILE_E164, PURPOSE, STATUS, CREATED_AT_UTC DESC, OTP_CHALLENGE_ID
);

CREATE INDEX SPLITO_IX_MOBILE_OTP_IP ON SPLITO_MOBILE_OTP_CHALLENGES (
  REQUEST_IP_HASH, CREATED_AT_UTC DESC, OTP_CHALLENGE_ID
);

CREATE TABLE SPLITO_MOBILE_OTP_THROTTLES (
  THROTTLE_SCOPE VARCHAR2(8 CHAR) NOT NULL,
  THROTTLE_KEY RAW(32) NOT NULL,
  WINDOW_STARTED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  REQUEST_COUNT NUMBER(10,0) DEFAULT 0 NOT NULL,
  LAST_ISSUED_AT_UTC TIMESTAMP(6),
  UPDATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT SPLITO_PK_MOBILE_OTP_THROTTLE PRIMARY KEY (THROTTLE_SCOPE, THROTTLE_KEY),
  CONSTRAINT SPLITO_CK_MOBILE_OTP_SCOPE CHECK (THROTTLE_SCOPE IN ('PHONE', 'IP')),
  CONSTRAINT SPLITO_CK_MOBILE_OTP_COUNT CHECK (REQUEST_COUNT BETWEEN 0 AND 9999999999)
);

CREATE INDEX SPLITO_IX_OTP_THROTTLE_AGE ON SPLITO_MOBILE_OTP_THROTTLES (UPDATED_AT_UTC);

UPDATE SPLITO_SESSIONS STALE
   SET REVOKED_AT_UTC = SYS_EXTRACT_UTC(SYSTIMESTAMP),
       REVOKED_REASON = 'SINGLE_ACTIVE_LOGIN'
 WHERE STALE.REVOKED_AT_UTC IS NULL
   AND EXISTS (
     SELECT 1
       FROM SPLITO_SESSIONS NEWER
      WHERE NEWER.USER_ID = STALE.USER_ID
        AND NEWER.REVOKED_AT_UTC IS NULL
        AND (
          NEWER.CREATED_AT_UTC > STALE.CREATED_AT_UTC OR
          (
            NEWER.CREATED_AT_UTC = STALE.CREATED_AT_UTC AND
            RAWTOHEX(NEWER.SESSION_ID) > RAWTOHEX(STALE.SESSION_ID)
          )
        )
   );

CREATE UNIQUE INDEX SPLITO_UQ_ONE_USER_SESSION ON SPLITO_SESSIONS (
  CASE WHEN REVOKED_AT_UTC IS NULL THEN USER_ID END
);

GRANT SELECT, INSERT, UPDATE ON SPLITO_MOBILE_OTP_CHALLENGES TO SPLITO_APP;
GRANT SELECT, INSERT, UPDATE ON SPLITO_MOBILE_OTP_THROTTLES TO SPLITO_APP;
