CREATE TABLE SPLITO_MEDIA_OBJECTS (
  MEDIA_ID RAW(16) NOT NULL,
  MEDIA_KIND VARCHAR2(20 CHAR) NOT NULL,
  OWNER_USER_ID RAW(16),
  OWNER_GROUP_ID RAW(16),
  UPLOADED_BY_PARTICIPANT_ID RAW(16) NOT NULL,
  STORAGE_PROVIDER VARCHAR2(30 CHAR) NOT NULL,
  STORAGE_KEY VARCHAR2(512 CHAR) NOT NULL,
  MEDIA_TYPE VARCHAR2(32 CHAR) NOT NULL,
  BYTE_SIZE NUMBER(10,0) NOT NULL,
  SHA256_HASH RAW(32) NOT NULL,
  WIDTH_PX NUMBER(5,0) NOT NULL,
  HEIGHT_PX NUMBER(5,0) NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT_UTC TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  SUPERSEDED_AT_UTC TIMESTAMP(6),
  DELETED_AT_UTC TIMESTAMP(6),
  CONSTRAINT SPLITO_PK_MEDIA_OBJECTS PRIMARY KEY (MEDIA_ID),
  CONSTRAINT SPLITO_UQ_MEDIA_STORAGE_KEY UNIQUE (STORAGE_KEY),
  CONSTRAINT SPLITO_UQ_MEDIA_USER_KEY UNIQUE (OWNER_USER_ID, STORAGE_KEY),
  CONSTRAINT SPLITO_UQ_MEDIA_GROUP_KEY UNIQUE (OWNER_GROUP_ID, STORAGE_KEY),
  CONSTRAINT SPLITO_FK_MEDIA_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES SPLITO_USERS (USER_ID),
  CONSTRAINT SPLITO_FK_MEDIA_GROUP FOREIGN KEY (OWNER_GROUP_ID) REFERENCES SPLITO_GROUPS (GROUP_ID),
  CONSTRAINT SPLITO_FK_MEDIA_UPLOADER FOREIGN KEY (UPLOADED_BY_PARTICIPANT_ID)
    REFERENCES SPLITO_PARTICIPANTS (PARTICIPANT_ID),
  CONSTRAINT SPLITO_CK_MEDIA_OWNER CHECK (
    (MEDIA_KIND = 'USER_AVATAR' AND OWNER_USER_ID IS NOT NULL AND OWNER_GROUP_ID IS NULL) OR
    (MEDIA_KIND = 'GROUP_IMAGE' AND OWNER_USER_ID IS NULL AND OWNER_GROUP_ID IS NOT NULL)
  ),
  CONSTRAINT SPLITO_CK_MEDIA_TYPE CHECK (MEDIA_TYPE = 'image/webp'),
  CONSTRAINT SPLITO_CK_MEDIA_SIZE CHECK (BYTE_SIZE BETWEEN 1 AND 10000000),
  CONSTRAINT SPLITO_CK_MEDIA_DIMENSIONS CHECK (
    WIDTH_PX BETWEEN 1 AND 4096 AND
    HEIGHT_PX BETWEEN 1 AND 4096 AND
    WIDTH_PX * HEIGHT_PX <= 16777216
  ),
  CONSTRAINT SPLITO_CK_MEDIA_STORAGE_KEY CHECK (
    STORAGE_KEY = TRIM(STORAGE_KEY) AND
    SUBSTR(STORAGE_KEY, 1, 1) <> '/' AND
    INSTR(STORAGE_KEY, '..') = 0 AND
    INSTR(STORAGE_KEY, '\') = 0
  ),
  CONSTRAINT SPLITO_CK_MEDIA_STATUS CHECK (STATUS IN ('ACTIVE', 'SUPERSEDED', 'DELETED')),
  CONSTRAINT SPLITO_CK_MEDIA_STATUS_DATES CHECK (
    (STATUS = 'ACTIVE' AND SUPERSEDED_AT_UTC IS NULL AND DELETED_AT_UTC IS NULL) OR
    (STATUS = 'SUPERSEDED' AND SUPERSEDED_AT_UTC IS NOT NULL AND DELETED_AT_UTC IS NULL) OR
    (STATUS = 'DELETED' AND DELETED_AT_UTC IS NOT NULL)
  )
);

CREATE UNIQUE INDEX SPLITO_UQ_MEDIA_ACTIVE_USER ON SPLITO_MEDIA_OBJECTS (
  CASE WHEN STATUS = 'ACTIVE' AND MEDIA_KIND = 'USER_AVATAR' THEN OWNER_USER_ID END
);

CREATE UNIQUE INDEX SPLITO_UQ_MEDIA_ACTIVE_GROUP ON SPLITO_MEDIA_OBJECTS (
  CASE WHEN STATUS = 'ACTIVE' AND MEDIA_KIND = 'GROUP_IMAGE' THEN OWNER_GROUP_ID END
);

CREATE INDEX SPLITO_IX_MEDIA_USER_HISTORY ON SPLITO_MEDIA_OBJECTS (
  OWNER_USER_ID, STATUS, CREATED_AT_UTC DESC, MEDIA_ID
);

CREATE INDEX SPLITO_IX_MEDIA_GROUP_HISTORY ON SPLITO_MEDIA_OBJECTS (
  OWNER_GROUP_ID, STATUS, CREATED_AT_UTC DESC, MEDIA_ID
);

CREATE INDEX SPLITO_IX_MEDIA_UPLOADER ON SPLITO_MEDIA_OBJECTS (
  UPLOADED_BY_PARTICIPANT_ID, CREATED_AT_UTC DESC, MEDIA_ID
);

ALTER TABLE SPLITO_USERS ADD CONSTRAINT SPLITO_FK_USER_AVATAR_MEDIA
  FOREIGN KEY (USER_ID, AVATAR_KEY)
  REFERENCES SPLITO_MEDIA_OBJECTS (OWNER_USER_ID, STORAGE_KEY);

ALTER TABLE SPLITO_GROUPS ADD CONSTRAINT SPLITO_FK_GROUP_IMAGE_MEDIA
  FOREIGN KEY (GROUP_ID, IMAGE_KEY)
  REFERENCES SPLITO_MEDIA_OBJECTS (OWNER_GROUP_ID, STORAGE_KEY);

GRANT SELECT, INSERT, UPDATE ON SPLITO_MEDIA_OBJECTS TO SPLITO_APP;
