ALTER TABLE SPLITO_INVITATIONS ADD INVITEE_MOBILE_E164 VARCHAR2(16 CHAR);

ALTER TABLE SPLITO_INVITATIONS DROP CONSTRAINT SPLITO_CK_INVITE_TARGET;

ALTER TABLE SPLITO_INVITATIONS ADD CONSTRAINT SPLITO_CK_INVITE_TARGET CHECK (
  INVITEE_EMAIL_NORMALIZED IS NOT NULL OR
  INVITEE_PARTICIPANT_ID IS NOT NULL OR
  INVITEE_MOBILE_E164 IS NOT NULL
);

ALTER TABLE SPLITO_INVITATIONS ADD CONSTRAINT SPLITO_CK_INVITE_MOBILE CHECK (
  INVITEE_MOBILE_E164 IS NULL OR
  REGEXP_LIKE(INVITEE_MOBILE_E164, '^\+[1-9][0-9]{7,14}$')
);

ALTER TABLE SPLITO_INVITATIONS ADD CONSTRAINT SPLITO_CK_INVITE_GROUP_CTX CHECK (
  INVITATION_TYPE <> 'GROUP' OR CONTEXT_ID IS NOT NULL
);

CREATE INDEX SPLITO_IX_INVITE_MOBILE ON SPLITO_INVITATIONS (
  INVITEE_MOBILE_E164, STATUS, EXPIRES_AT_UTC
);

CREATE UNIQUE INDEX SPLITO_UQ_PENDING_GRP_MOBILE ON SPLITO_INVITATIONS (
  CASE
    WHEN INVITATION_TYPE = 'GROUP' AND STATUS = 'PENDING' AND INVITEE_MOBILE_E164 IS NOT NULL
      THEN CONTEXT_ID
  END,
  CASE
    WHEN INVITATION_TYPE = 'GROUP' AND STATUS = 'PENDING' AND INVITEE_MOBILE_E164 IS NOT NULL
      THEN INVITEE_MOBILE_E164
  END
);
